// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: internal/proto/physicalResource.proto

package physicalresource

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PhysicalResource_ResourceStatus int32

const (
	PhysicalResource_Created   PhysicalResource_ResourceStatus = 0
	PhysicalResource_Available PhysicalResource_ResourceStatus = 1
	PhysicalResource_Reserved  PhysicalResource_ResourceStatus = 2
	PhysicalResource_InUse     PhysicalResource_ResourceStatus = 3
	PhysicalResource_Retired   PhysicalResource_ResourceStatus = 4
	PhysicalResource_Disabled  PhysicalResource_ResourceStatus = 5
)

// Enum value maps for PhysicalResource_ResourceStatus.
var (
	PhysicalResource_ResourceStatus_name = map[int32]string{
		0: "Created",
		1: "Available",
		2: "Reserved",
		3: "InUse",
		4: "Retired",
		5: "Disabled",
	}
	PhysicalResource_ResourceStatus_value = map[string]int32{
		"Created":   0,
		"Available": 1,
		"Reserved":  2,
		"InUse":     3,
		"Retired":   4,
		"Disabled":  5,
	}
)

func (x PhysicalResource_ResourceStatus) Enum() *PhysicalResource_ResourceStatus {
	p := new(PhysicalResource_ResourceStatus)
	*p = x
	return p
}

func (x PhysicalResource_ResourceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PhysicalResource_ResourceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_physicalResource_proto_enumTypes[0].Descriptor()
}

func (PhysicalResource_ResourceStatus) Type() protoreflect.EnumType {
	return &file_internal_proto_physicalResource_proto_enumTypes[0]
}

func (x PhysicalResource_ResourceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PhysicalResource_ResourceStatus.Descriptor instead.
func (PhysicalResource_ResourceStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_physicalResource_proto_rawDescGZIP(), []int{0, 0}
}

type PhysicalResource_ResourceRelationship_RelationshipType int32

const (
	PhysicalResource_ResourceRelationship_reliesOn    PhysicalResource_ResourceRelationship_RelationshipType = 0
	PhysicalResource_ResourceRelationship_bundle      PhysicalResource_ResourceRelationship_RelationshipType = 1
	PhysicalResource_ResourceRelationship_dependency  PhysicalResource_ResourceRelationship_RelationshipType = 2
	PhysicalResource_ResourceRelationship_starterPack PhysicalResource_ResourceRelationship_RelationshipType = 3
	PhysicalResource_ResourceRelationship_capacity    PhysicalResource_ResourceRelationship_RelationshipType = 4
	PhysicalResource_ResourceRelationship_pool        PhysicalResource_ResourceRelationship_RelationshipType = 5
)

// Enum value maps for PhysicalResource_ResourceRelationship_RelationshipType.
var (
	PhysicalResource_ResourceRelationship_RelationshipType_name = map[int32]string{
		0: "reliesOn",
		1: "bundle",
		2: "dependency",
		3: "starterPack",
		4: "capacity",
		5: "pool",
	}
	PhysicalResource_ResourceRelationship_RelationshipType_value = map[string]int32{
		"reliesOn":    0,
		"bundle":      1,
		"dependency":  2,
		"starterPack": 3,
		"capacity":    4,
		"pool":        5,
	}
)

func (x PhysicalResource_ResourceRelationship_RelationshipType) Enum() *PhysicalResource_ResourceRelationship_RelationshipType {
	p := new(PhysicalResource_ResourceRelationship_RelationshipType)
	*p = x
	return p
}

func (x PhysicalResource_ResourceRelationship_RelationshipType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PhysicalResource_ResourceRelationship_RelationshipType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_physicalResource_proto_enumTypes[1].Descriptor()
}

func (PhysicalResource_ResourceRelationship_RelationshipType) Type() protoreflect.EnumType {
	return &file_internal_proto_physicalResource_proto_enumTypes[1]
}

func (x PhysicalResource_ResourceRelationship_RelationshipType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PhysicalResource_ResourceRelationship_RelationshipType.Descriptor instead.
func (PhysicalResource_ResourceRelationship_RelationshipType) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_physicalResource_proto_rawDescGZIP(), []int{0, 4, 0}
}

type PhysicalResourceResponse_ResourceStatus int32

const (
	PhysicalResourceResponse_Created   PhysicalResourceResponse_ResourceStatus = 0
	PhysicalResourceResponse_Available PhysicalResourceResponse_ResourceStatus = 1
	PhysicalResourceResponse_Reserved  PhysicalResourceResponse_ResourceStatus = 2
	PhysicalResourceResponse_InUse     PhysicalResourceResponse_ResourceStatus = 3
	PhysicalResourceResponse_Retired   PhysicalResourceResponse_ResourceStatus = 4
	PhysicalResourceResponse_Disabled  PhysicalResourceResponse_ResourceStatus = 5
)

// Enum value maps for PhysicalResourceResponse_ResourceStatus.
var (
	PhysicalResourceResponse_ResourceStatus_name = map[int32]string{
		0: "Created",
		1: "Available",
		2: "Reserved",
		3: "InUse",
		4: "Retired",
		5: "Disabled",
	}
	PhysicalResourceResponse_ResourceStatus_value = map[string]int32{
		"Created":   0,
		"Available": 1,
		"Reserved":  2,
		"InUse":     3,
		"Retired":   4,
		"Disabled":  5,
	}
)

func (x PhysicalResourceResponse_ResourceStatus) Enum() *PhysicalResourceResponse_ResourceStatus {
	p := new(PhysicalResourceResponse_ResourceStatus)
	*p = x
	return p
}

func (x PhysicalResourceResponse_ResourceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PhysicalResourceResponse_ResourceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_physicalResource_proto_enumTypes[2].Descriptor()
}

func (PhysicalResourceResponse_ResourceStatus) Type() protoreflect.EnumType {
	return &file_internal_proto_physicalResource_proto_enumTypes[2]
}

func (x PhysicalResourceResponse_ResourceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PhysicalResourceResponse_ResourceStatus.Descriptor instead.
func (PhysicalResourceResponse_ResourceStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_physicalResource_proto_rawDescGZIP(), []int{1, 0}
}

type PhysicalResourceResponse_ResourceRelationship_RelationshipType int32

const (
	PhysicalResourceResponse_ResourceRelationship_reliesOn    PhysicalResourceResponse_ResourceRelationship_RelationshipType = 0
	PhysicalResourceResponse_ResourceRelationship_bundle      PhysicalResourceResponse_ResourceRelationship_RelationshipType = 1
	PhysicalResourceResponse_ResourceRelationship_dependency  PhysicalResourceResponse_ResourceRelationship_RelationshipType = 2
	PhysicalResourceResponse_ResourceRelationship_starterPack PhysicalResourceResponse_ResourceRelationship_RelationshipType = 3
	PhysicalResourceResponse_ResourceRelationship_capacity    PhysicalResourceResponse_ResourceRelationship_RelationshipType = 4
	PhysicalResourceResponse_ResourceRelationship_pool        PhysicalResourceResponse_ResourceRelationship_RelationshipType = 5
)

// Enum value maps for PhysicalResourceResponse_ResourceRelationship_RelationshipType.
var (
	PhysicalResourceResponse_ResourceRelationship_RelationshipType_name = map[int32]string{
		0: "reliesOn",
		1: "bundle",
		2: "dependency",
		3: "starterPack",
		4: "capacity",
		5: "pool",
	}
	PhysicalResourceResponse_ResourceRelationship_RelationshipType_value = map[string]int32{
		"reliesOn":    0,
		"bundle":      1,
		"dependency":  2,
		"starterPack": 3,
		"capacity":    4,
		"pool":        5,
	}
)

func (x PhysicalResourceResponse_ResourceRelationship_RelationshipType) Enum() *PhysicalResourceResponse_ResourceRelationship_RelationshipType {
	p := new(PhysicalResourceResponse_ResourceRelationship_RelationshipType)
	*p = x
	return p
}

func (x PhysicalResourceResponse_ResourceRelationship_RelationshipType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PhysicalResourceResponse_ResourceRelationship_RelationshipType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_physicalResource_proto_enumTypes[3].Descriptor()
}

func (PhysicalResourceResponse_ResourceRelationship_RelationshipType) Type() protoreflect.EnumType {
	return &file_internal_proto_physicalResource_proto_enumTypes[3]
}

func (x PhysicalResourceResponse_ResourceRelationship_RelationshipType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PhysicalResourceResponse_ResourceRelationship_RelationshipType.Descriptor instead.
func (PhysicalResourceResponse_ResourceRelationship_RelationshipType) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_physicalResource_proto_rawDescGZIP(), []int{1, 4, 0}
}

type PhysicalResource struct {
	state                  protoimpl.MessageState                     `protogen:"open.v1"`
	Id                     string                                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description            string                                     `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Name                   string                                     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type                   string                                     `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	BaseType               string                                     `protobuf:"bytes,5,opt,name=baseType,proto3" json:"baseType,omitempty"`
	IsBundle               bool                                       `protobuf:"varint,6,opt,name=isBundle,proto3" json:"isBundle,omitempty"`
	Value                  string                                     `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	StartOperatingDate     string                                     `protobuf:"bytes,8,opt,name=startOperatingDate,proto3" json:"startOperatingDate,omitempty"`
	EndOperatingDate       string                                     `protobuf:"bytes,9,opt,name=endOperatingDate,proto3" json:"endOperatingDate,omitempty"`
	ResourceRecycleDate    string                                     `protobuf:"bytes,10,opt,name=resourceRecycleDate,proto3" json:"resourceRecycleDate,omitempty"`
	ResourceStatus         string                                     `protobuf:"bytes,11,opt,name=resourceStatus,proto3" json:"resourceStatus,omitempty"`
	BusinessType           []string                                   `protobuf:"bytes,12,rep,name=businessType,proto3" json:"businessType,omitempty"`
	Category               []string                                   `protobuf:"bytes,13,rep,name=category,proto3" json:"category,omitempty"`
	Cost                   *PhysicalResource_Cost                     `protobuf:"bytes,14,opt,name=cost,proto3" json:"cost,omitempty"`
	Note                   []*PhysicalResource_Note                   `protobuf:"bytes,15,rep,name=note,proto3" json:"note,omitempty"`
	RelatedParty           []*PhysicalResource_RelatedParty           `protobuf:"bytes,16,rep,name=relatedParty,proto3" json:"relatedParty,omitempty"`
	ResourceCharacteristic []*PhysicalResource_ResourceCharacteristic `protobuf:"bytes,17,rep,name=resourceCharacteristic,proto3" json:"resourceCharacteristic,omitempty"`
	ResourceRelationship   []*PhysicalResource_ResourceRelationship   `protobuf:"bytes,18,rep,name=resourceRelationship,proto3" json:"resourceRelationship,omitempty"`
	BundledResources       []*PhysicalResource_BundledResources       `protobuf:"bytes,19,rep,name=bundledResources,proto3" json:"bundledResources,omitempty"`
	CreatedAt              string                                     `protobuf:"bytes,20,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt              string                                     `protobuf:"bytes,21,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PhysicalResource) Reset() {
	*x = PhysicalResource{}
	mi := &file_internal_proto_physicalResource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalResource) ProtoMessage() {}

func (x *PhysicalResource) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_physicalResource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalResource.ProtoReflect.Descriptor instead.
func (*PhysicalResource) Descriptor() ([]byte, []int) {
	return file_internal_proto_physicalResource_proto_rawDescGZIP(), []int{0}
}

func (x *PhysicalResource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PhysicalResource) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PhysicalResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PhysicalResource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PhysicalResource) GetBaseType() string {
	if x != nil {
		return x.BaseType
	}
	return ""
}

func (x *PhysicalResource) GetIsBundle() bool {
	if x != nil {
		return x.IsBundle
	}
	return false
}

func (x *PhysicalResource) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PhysicalResource) GetStartOperatingDate() string {
	if x != nil {
		return x.StartOperatingDate
	}
	return ""
}

func (x *PhysicalResource) GetEndOperatingDate() string {
	if x != nil {
		return x.EndOperatingDate
	}
	return ""
}

func (x *PhysicalResource) GetResourceRecycleDate() string {
	if x != nil {
		return x.ResourceRecycleDate
	}
	return ""
}

func (x *PhysicalResource) GetResourceStatus() string {
	if x != nil {
		return x.ResourceStatus
	}
	return ""
}

func (x *PhysicalResource) GetBusinessType() []string {
	if x != nil {
		return x.BusinessType
	}
	return nil
}

func (x *PhysicalResource) GetCategory() []string {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *PhysicalResource) GetCost() *PhysicalResource_Cost {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *PhysicalResource) GetNote() []*PhysicalResource_Note {
	if x != nil {
		return x.Note
	}
	return nil
}

func (x *PhysicalResource) GetRelatedParty() []*PhysicalResource_RelatedParty {
	if x != nil {
		return x.RelatedParty
	}
	return nil
}

func (x *PhysicalResource) GetResourceCharacteristic() []*PhysicalResource_ResourceCharacteristic {
	if x != nil {
		return x.ResourceCharacteristic
	}
	return nil
}

func (x *PhysicalResource) GetResourceRelationship() []*PhysicalResource_ResourceRelationship {
	if x != nil {
		return x.ResourceRelationship
	}
	return nil
}

func (x *PhysicalResource) GetBundledResources() []*PhysicalResource_BundledResources {
	if x != nil {
		return x.BundledResources
	}
	return nil
}

func (x *PhysicalResource) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PhysicalResource) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type PhysicalResourceResponse struct {
	state                  protoimpl.MessageState                             `protogen:"open.v1"`
	Id                     string                                             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description            string                                             `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Name                   string                                             `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type                   string                                             `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	BaseType               string                                             `protobuf:"bytes,5,opt,name=baseType,proto3" json:"baseType,omitempty"`
	IsBundle               bool                                               `protobuf:"varint,6,opt,name=isBundle,proto3" json:"isBundle,omitempty"`
	Value                  string                                             `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	StartOperatingDate     string                                             `protobuf:"bytes,8,opt,name=startOperatingDate,proto3" json:"startOperatingDate,omitempty"`
	EndOperatingDate       string                                             `protobuf:"bytes,9,opt,name=endOperatingDate,proto3" json:"endOperatingDate,omitempty"`
	ResourceRecycleDate    string                                             `protobuf:"bytes,10,opt,name=resourceRecycleDate,proto3" json:"resourceRecycleDate,omitempty"`
	ResourceStatus         string                                             `protobuf:"bytes,11,opt,name=resourceStatus,proto3" json:"resourceStatus,omitempty"`
	BusinessType           []string                                           `protobuf:"bytes,12,rep,name=businessType,proto3" json:"businessType,omitempty"`
	Category               []string                                           `protobuf:"bytes,13,rep,name=category,proto3" json:"category,omitempty"`
	Cost                   *PhysicalResourceResponse_Cost                     `protobuf:"bytes,14,opt,name=cost,proto3" json:"cost,omitempty"`
	Note                   []*PhysicalResourceResponse_Note                   `protobuf:"bytes,15,rep,name=note,proto3" json:"note,omitempty"`
	RelatedParty           []*PhysicalResourceResponse_RelatedParty           `protobuf:"bytes,16,rep,name=relatedParty,proto3" json:"relatedParty,omitempty"`
	ResourceCharacteristic []*PhysicalResourceResponse_ResourceCharacteristic `protobuf:"bytes,17,rep,name=resourceCharacteristic,proto3" json:"resourceCharacteristic,omitempty"`
	ResourceRelationship   []*PhysicalResourceResponse_ResourceRelationship   `protobuf:"bytes,18,rep,name=resourceRelationship,proto3" json:"resourceRelationship,omitempty"`
	BundledResources       []*PhysicalResourceResponse_BundledResources       `protobuf:"bytes,19,rep,name=bundledResources,proto3" json:"bundledResources,omitempty"`
	CreatedAt              string                                             `protobuf:"bytes,20,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt              string                                             `protobuf:"bytes,21,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PhysicalResourceResponse) Reset() {
	*x = PhysicalResourceResponse{}
	mi := &file_internal_proto_physicalResource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalResourceResponse) ProtoMessage() {}

func (x *PhysicalResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_physicalResource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalResourceResponse.ProtoReflect.Descriptor instead.
func (*PhysicalResourceResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_physicalResource_proto_rawDescGZIP(), []int{1}
}

func (x *PhysicalResourceResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PhysicalResourceResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PhysicalResourceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PhysicalResourceResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PhysicalResourceResponse) GetBaseType() string {
	if x != nil {
		return x.BaseType
	}
	return ""
}

func (x *PhysicalResourceResponse) GetIsBundle() bool {
	if x != nil {
		return x.IsBundle
	}
	return false
}

func (x *PhysicalResourceResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PhysicalResourceResponse) GetStartOperatingDate() string {
	if x != nil {
		return x.StartOperatingDate
	}
	return ""
}

func (x *PhysicalResourceResponse) GetEndOperatingDate() string {
	if x != nil {
		return x.EndOperatingDate
	}
	return ""
}

func (x *PhysicalResourceResponse) GetResourceRecycleDate() string {
	if x != nil {
		return x.ResourceRecycleDate
	}
	return ""
}

func (x *PhysicalResourceResponse) GetResourceStatus() string {
	if x != nil {
		return x.ResourceStatus
	}
	return ""
}

func (x *PhysicalResourceResponse) GetBusinessType() []string {
	if x != nil {
		return x.BusinessType
	}
	return nil
}

func (x *PhysicalResourceResponse) GetCategory() []string {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *PhysicalResourceResponse) GetCost() *PhysicalResourceResponse_Cost {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *PhysicalResourceResponse) GetNote() []*PhysicalResourceResponse_Note {
	if x != nil {
		return x.Note
	}
	return nil
}

func (x *PhysicalResourceResponse) GetRelatedParty() []*PhysicalResourceResponse_RelatedParty {
	if x != nil {
		return x.RelatedParty
	}
	return nil
}

func (x *PhysicalResourceResponse) GetResourceCharacteristic() []*PhysicalResourceResponse_ResourceCharacteristic {
	if x != nil {
		return x.ResourceCharacteristic
	}
	return nil
}

func (x *PhysicalResourceResponse) GetResourceRelationship() []*PhysicalResourceResponse_ResourceRelationship {
	if x != nil {
		return x.ResourceRelationship
	}
	return nil
}

func (x *PhysicalResourceResponse) GetBundledResources() []*PhysicalResourceResponse_BundledResources {
	if x != nil {
		return x.BundledResources
	}
	return nil
}

func (x *PhysicalResourceResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PhysicalResourceResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type PatchPhysicalRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PhysicalResource *PhysicalResource      `protobuf:"bytes,2,opt,name=physicalResource,proto3" json:"physicalResource,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PatchPhysicalRequest) Reset() {
	*x = PatchPhysicalRequest{}
	mi := &file_internal_proto_physicalResource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchPhysicalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchPhysicalRequest) ProtoMessage() {}

func (x *PatchPhysicalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_physicalResource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchPhysicalRequest.ProtoReflect.Descriptor instead.
func (*PatchPhysicalRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_physicalResource_proto_rawDescGZIP(), []int{2}
}

func (x *PatchPhysicalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PatchPhysicalRequest) GetPhysicalResource() *PhysicalResource {
	if x != nil {
		return x.PhysicalResource
	}
	return nil
}

type PhysicalResource_Cost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaxFreeValue  int64                  `protobuf:"varint,1,opt,name=taxFreeValue,proto3" json:"taxFreeValue,omitempty"`
	TaxedValue    int64                  `protobuf:"varint,2,opt,name=taxedValue,proto3" json:"taxedValue,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhysicalResource_Cost) Reset() {
	*x = PhysicalResource_Cost{}
	mi := &file_internal_proto_physicalResource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalResource_Cost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalResource_Cost) ProtoMessage() {}

func (x *PhysicalResource_Cost) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_physicalResource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalResource_Cost.ProtoReflect.Descriptor instead.
func (*PhysicalResource_Cost) Descriptor() ([]byte, []int) {
	return file_internal_proto_physicalResource_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PhysicalResource_Cost) GetTaxFreeValue() int64 {
	if x != nil {
		return x.TaxFreeValue
	}
	return 0
}

func (x *PhysicalResource_Cost) GetTaxedValue() int64 {
	if x != nil {
		return x.TaxedValue
	}
	return 0
}

func (x *PhysicalResource_Cost) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type PhysicalResource_Note struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorRole    string                 `protobuf:"bytes,1,opt,name=authorRole,proto3" json:"authorRole,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"` // ISO date string
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhysicalResource_Note) Reset() {
	*x = PhysicalResource_Note{}
	mi := &file_internal_proto_physicalResource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalResource_Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalResource_Note) ProtoMessage() {}

func (x *PhysicalResource_Note) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_physicalResource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalResource_Note.ProtoReflect.Descriptor instead.
func (*PhysicalResource_Note) Descriptor() ([]byte, []int) {
	return file_internal_proto_physicalResource_proto_rawDescGZIP(), []int{0, 1}
}

func (x *PhysicalResource_Note) GetAuthorRole() string {
	if x != nil {
		return x.AuthorRole
	}
	return ""
}

func (x *PhysicalResource_Note) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PhysicalResource_Note) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *PhysicalResource_Note) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PhysicalResource_RelatedParty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	BaseType      string                 `protobuf:"bytes,4,opt,name=baseType,proto3" json:"baseType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhysicalResource_RelatedParty) Reset() {
	*x = PhysicalResource_RelatedParty{}
	mi := &file_internal_proto_physicalResource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalResource_RelatedParty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalResource_RelatedParty) ProtoMessage() {}

func (x *PhysicalResource_RelatedParty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_physicalResource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalResource_RelatedParty.ProtoReflect.Descriptor instead.
func (*PhysicalResource_RelatedParty) Descriptor() ([]byte, []int) {
	return file_internal_proto_physicalResource_proto_rawDescGZIP(), []int{0, 2}
}

func (x *PhysicalResource_RelatedParty) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PhysicalResource_RelatedParty) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *PhysicalResource_RelatedParty) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PhysicalResource_RelatedParty) GetBaseType() string {
	if x != nil {
		return x.BaseType
	}
	return ""
}

type PhysicalResource_ResourceCharacteristic struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Code             string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PublicIdentifier bool                   `protobuf:"varint,3,opt,name=publicIdentifier,proto3" json:"publicIdentifier,omitempty"`
	Value            string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	ValueType        string                 `protobuf:"bytes,5,opt,name=valueType,proto3" json:"valueType,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PhysicalResource_ResourceCharacteristic) Reset() {
	*x = PhysicalResource_ResourceCharacteristic{}
	mi := &file_internal_proto_physicalResource_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalResource_ResourceCharacteristic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalResource_ResourceCharacteristic) ProtoMessage() {}

func (x *PhysicalResource_ResourceCharacteristic) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_physicalResource_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalResource_ResourceCharacteristic.ProtoReflect.Descriptor instead.
func (*PhysicalResource_ResourceCharacteristic) Descriptor() ([]byte, []int) {
	return file_internal_proto_physicalResource_proto_rawDescGZIP(), []int{0, 3}
}

func (x *PhysicalResource_ResourceCharacteristic) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PhysicalResource_ResourceCharacteristic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PhysicalResource_ResourceCharacteristic) GetPublicIdentifier() bool {
	if x != nil {
		return x.PublicIdentifier
	}
	return false
}

func (x *PhysicalResource_ResourceCharacteristic) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PhysicalResource_ResourceCharacteristic) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

// ResourceRelationship of the LogicalResourceMessage task
type PhysicalResource_ResourceRelationship struct {
	state            protoimpl.MessageState                          `protogen:"open.v1"`
	RelationshipType string                                          `protobuf:"bytes,1,opt,name=relationshipType,proto3" json:"relationshipType,omitempty"`
	ValidFor         *PhysicalResource_ResourceRelationship_ValidFor `protobuf:"bytes,2,opt,name=validFor,proto3" json:"validFor,omitempty"`
	Resource         *PhysicalResource_ResourceRelationship_Resource `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PhysicalResource_ResourceRelationship) Reset() {
	*x = PhysicalResource_ResourceRelationship{}
	mi := &file_internal_proto_physicalResource_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalResource_ResourceRelationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalResource_ResourceRelationship) ProtoMessage() {}

func (x *PhysicalResource_ResourceRelationship) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_physicalResource_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalResource_ResourceRelationship.ProtoReflect.Descriptor instead.
func (*PhysicalResource_ResourceRelationship) Descriptor() ([]byte, []int) {
	return file_internal_proto_physicalResource_proto_rawDescGZIP(), []int{0, 4}
}

func (x *PhysicalResource_ResourceRelationship) GetRelationshipType() string {
	if x != nil {
		return x.RelationshipType
	}
	return ""
}

func (x *PhysicalResource_ResourceRelationship) GetValidFor() *PhysicalResource_ResourceRelationship_ValidFor {
	if x != nil {
		return x.ValidFor
	}
	return nil
}

func (x *PhysicalResource_ResourceRelationship) GetResource() *PhysicalResource_ResourceRelationship_Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type PhysicalResource_BundledResources struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Href           string                 `protobuf:"bytes,2,opt,name=href,proto3" json:"href,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	BaseType       string                 `protobuf:"bytes,4,opt,name=baseType,proto3" json:"baseType,omitempty"`
	SchemaLocation string                 `protobuf:"bytes,5,opt,name=schemaLocation,proto3" json:"schemaLocation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PhysicalResource_BundledResources) Reset() {
	*x = PhysicalResource_BundledResources{}
	mi := &file_internal_proto_physicalResource_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalResource_BundledResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalResource_BundledResources) ProtoMessage() {}

func (x *PhysicalResource_BundledResources) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_physicalResource_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalResource_BundledResources.ProtoReflect.Descriptor instead.
func (*PhysicalResource_BundledResources) Descriptor() ([]byte, []int) {
	return file_internal_proto_physicalResource_proto_rawDescGZIP(), []int{0, 5}
}

func (x *PhysicalResource_BundledResources) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PhysicalResource_BundledResources) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

func (x *PhysicalResource_BundledResources) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PhysicalResource_BundledResources) GetBaseType() string {
	if x != nil {
		return x.BaseType
	}
	return ""
}

func (x *PhysicalResource_BundledResources) GetSchemaLocation() string {
	if x != nil {
		return x.SchemaLocation
	}
	return ""
}

type PhysicalResource_ResourceRelationship_ValidFor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDateTime string                 `protobuf:"bytes,1,opt,name=startDateTime,proto3" json:"startDateTime,omitempty"`
	EndDateTime   string                 `protobuf:"bytes,2,opt,name=endDateTime,proto3" json:"endDateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhysicalResource_ResourceRelationship_ValidFor) Reset() {
	*x = PhysicalResource_ResourceRelationship_ValidFor{}
	mi := &file_internal_proto_physicalResource_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalResource_ResourceRelationship_ValidFor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalResource_ResourceRelationship_ValidFor) ProtoMessage() {}

func (x *PhysicalResource_ResourceRelationship_ValidFor) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_physicalResource_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalResource_ResourceRelationship_ValidFor.ProtoReflect.Descriptor instead.
func (*PhysicalResource_ResourceRelationship_ValidFor) Descriptor() ([]byte, []int) {
	return file_internal_proto_physicalResource_proto_rawDescGZIP(), []int{0, 4, 0}
}

func (x *PhysicalResource_ResourceRelationship_ValidFor) GetStartDateTime() string {
	if x != nil {
		return x.StartDateTime
	}
	return ""
}

func (x *PhysicalResource_ResourceRelationship_ValidFor) GetEndDateTime() string {
	if x != nil {
		return x.EndDateTime
	}
	return ""
}

type PhysicalResource_ResourceRelationship_Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	BaseType      string                 `protobuf:"bytes,3,opt,name=baseType,proto3" json:"baseType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhysicalResource_ResourceRelationship_Resource) Reset() {
	*x = PhysicalResource_ResourceRelationship_Resource{}
	mi := &file_internal_proto_physicalResource_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalResource_ResourceRelationship_Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalResource_ResourceRelationship_Resource) ProtoMessage() {}

func (x *PhysicalResource_ResourceRelationship_Resource) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_physicalResource_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalResource_ResourceRelationship_Resource.ProtoReflect.Descriptor instead.
func (*PhysicalResource_ResourceRelationship_Resource) Descriptor() ([]byte, []int) {
	return file_internal_proto_physicalResource_proto_rawDescGZIP(), []int{0, 4, 1}
}

func (x *PhysicalResource_ResourceRelationship_Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PhysicalResource_ResourceRelationship_Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PhysicalResource_ResourceRelationship_Resource) GetBaseType() string {
	if x != nil {
		return x.BaseType
	}
	return ""
}

type PhysicalResourceResponse_Cost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaxFreeValue  int64                  `protobuf:"varint,1,opt,name=taxFreeValue,proto3" json:"taxFreeValue,omitempty"`
	TaxedValue    int64                  `protobuf:"varint,2,opt,name=taxedValue,proto3" json:"taxedValue,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhysicalResourceResponse_Cost) Reset() {
	*x = PhysicalResourceResponse_Cost{}
	mi := &file_internal_proto_physicalResource_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalResourceResponse_Cost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalResourceResponse_Cost) ProtoMessage() {}

func (x *PhysicalResourceResponse_Cost) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_physicalResource_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalResourceResponse_Cost.ProtoReflect.Descriptor instead.
func (*PhysicalResourceResponse_Cost) Descriptor() ([]byte, []int) {
	return file_internal_proto_physicalResource_proto_rawDescGZIP(), []int{1, 0}
}

func (x *PhysicalResourceResponse_Cost) GetTaxFreeValue() int64 {
	if x != nil {
		return x.TaxFreeValue
	}
	return 0
}

func (x *PhysicalResourceResponse_Cost) GetTaxedValue() int64 {
	if x != nil {
		return x.TaxedValue
	}
	return 0
}

func (x *PhysicalResourceResponse_Cost) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type PhysicalResourceResponse_Note struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorRole    string                 `protobuf:"bytes,1,opt,name=authorRole,proto3" json:"authorRole,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"` // ISO date string
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhysicalResourceResponse_Note) Reset() {
	*x = PhysicalResourceResponse_Note{}
	mi := &file_internal_proto_physicalResource_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalResourceResponse_Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalResourceResponse_Note) ProtoMessage() {}

func (x *PhysicalResourceResponse_Note) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_physicalResource_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalResourceResponse_Note.ProtoReflect.Descriptor instead.
func (*PhysicalResourceResponse_Note) Descriptor() ([]byte, []int) {
	return file_internal_proto_physicalResource_proto_rawDescGZIP(), []int{1, 1}
}

func (x *PhysicalResourceResponse_Note) GetAuthorRole() string {
	if x != nil {
		return x.AuthorRole
	}
	return ""
}

func (x *PhysicalResourceResponse_Note) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PhysicalResourceResponse_Note) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *PhysicalResourceResponse_Note) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PhysicalResourceResponse_RelatedParty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	BaseType      string                 `protobuf:"bytes,4,opt,name=baseType,proto3" json:"baseType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhysicalResourceResponse_RelatedParty) Reset() {
	*x = PhysicalResourceResponse_RelatedParty{}
	mi := &file_internal_proto_physicalResource_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalResourceResponse_RelatedParty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalResourceResponse_RelatedParty) ProtoMessage() {}

func (x *PhysicalResourceResponse_RelatedParty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_physicalResource_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalResourceResponse_RelatedParty.ProtoReflect.Descriptor instead.
func (*PhysicalResourceResponse_RelatedParty) Descriptor() ([]byte, []int) {
	return file_internal_proto_physicalResource_proto_rawDescGZIP(), []int{1, 2}
}

func (x *PhysicalResourceResponse_RelatedParty) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PhysicalResourceResponse_RelatedParty) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *PhysicalResourceResponse_RelatedParty) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PhysicalResourceResponse_RelatedParty) GetBaseType() string {
	if x != nil {
		return x.BaseType
	}
	return ""
}

type PhysicalResourceResponse_ResourceCharacteristic struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Code             string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PublicIdentifier bool                   `protobuf:"varint,3,opt,name=publicIdentifier,proto3" json:"publicIdentifier,omitempty"`
	Value            string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	ValueType        string                 `protobuf:"bytes,5,opt,name=valueType,proto3" json:"valueType,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PhysicalResourceResponse_ResourceCharacteristic) Reset() {
	*x = PhysicalResourceResponse_ResourceCharacteristic{}
	mi := &file_internal_proto_physicalResource_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalResourceResponse_ResourceCharacteristic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalResourceResponse_ResourceCharacteristic) ProtoMessage() {}

func (x *PhysicalResourceResponse_ResourceCharacteristic) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_physicalResource_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalResourceResponse_ResourceCharacteristic.ProtoReflect.Descriptor instead.
func (*PhysicalResourceResponse_ResourceCharacteristic) Descriptor() ([]byte, []int) {
	return file_internal_proto_physicalResource_proto_rawDescGZIP(), []int{1, 3}
}

func (x *PhysicalResourceResponse_ResourceCharacteristic) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PhysicalResourceResponse_ResourceCharacteristic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PhysicalResourceResponse_ResourceCharacteristic) GetPublicIdentifier() bool {
	if x != nil {
		return x.PublicIdentifier
	}
	return false
}

func (x *PhysicalResourceResponse_ResourceCharacteristic) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PhysicalResourceResponse_ResourceCharacteristic) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

// ResourceRelationship of the LogicalResourceMessage task
type PhysicalResourceResponse_ResourceRelationship struct {
	state            protoimpl.MessageState                                  `protogen:"open.v1"`
	RelationshipType string                                                  `protobuf:"bytes,1,opt,name=relationshipType,proto3" json:"relationshipType,omitempty"`
	ValidFor         *PhysicalResourceResponse_ResourceRelationship_ValidFor `protobuf:"bytes,2,opt,name=validFor,proto3" json:"validFor,omitempty"`
	Resource         *PhysicalResourceResponse_ResourceRelationship_Resource `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PhysicalResourceResponse_ResourceRelationship) Reset() {
	*x = PhysicalResourceResponse_ResourceRelationship{}
	mi := &file_internal_proto_physicalResource_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalResourceResponse_ResourceRelationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalResourceResponse_ResourceRelationship) ProtoMessage() {}

func (x *PhysicalResourceResponse_ResourceRelationship) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_physicalResource_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalResourceResponse_ResourceRelationship.ProtoReflect.Descriptor instead.
func (*PhysicalResourceResponse_ResourceRelationship) Descriptor() ([]byte, []int) {
	return file_internal_proto_physicalResource_proto_rawDescGZIP(), []int{1, 4}
}

func (x *PhysicalResourceResponse_ResourceRelationship) GetRelationshipType() string {
	if x != nil {
		return x.RelationshipType
	}
	return ""
}

func (x *PhysicalResourceResponse_ResourceRelationship) GetValidFor() *PhysicalResourceResponse_ResourceRelationship_ValidFor {
	if x != nil {
		return x.ValidFor
	}
	return nil
}

func (x *PhysicalResourceResponse_ResourceRelationship) GetResource() *PhysicalResourceResponse_ResourceRelationship_Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type PhysicalResourceResponse_BundledResources struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Href           string                 `protobuf:"bytes,2,opt,name=href,proto3" json:"href,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	BaseType       string                 `protobuf:"bytes,4,opt,name=baseType,proto3" json:"baseType,omitempty"`
	SchemaLocation string                 `protobuf:"bytes,5,opt,name=schemaLocation,proto3" json:"schemaLocation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PhysicalResourceResponse_BundledResources) Reset() {
	*x = PhysicalResourceResponse_BundledResources{}
	mi := &file_internal_proto_physicalResource_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalResourceResponse_BundledResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalResourceResponse_BundledResources) ProtoMessage() {}

func (x *PhysicalResourceResponse_BundledResources) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_physicalResource_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalResourceResponse_BundledResources.ProtoReflect.Descriptor instead.
func (*PhysicalResourceResponse_BundledResources) Descriptor() ([]byte, []int) {
	return file_internal_proto_physicalResource_proto_rawDescGZIP(), []int{1, 5}
}

func (x *PhysicalResourceResponse_BundledResources) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PhysicalResourceResponse_BundledResources) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

func (x *PhysicalResourceResponse_BundledResources) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PhysicalResourceResponse_BundledResources) GetBaseType() string {
	if x != nil {
		return x.BaseType
	}
	return ""
}

func (x *PhysicalResourceResponse_BundledResources) GetSchemaLocation() string {
	if x != nil {
		return x.SchemaLocation
	}
	return ""
}

type PhysicalResourceResponse_ResourceRelationship_ValidFor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDateTime string                 `protobuf:"bytes,1,opt,name=startDateTime,proto3" json:"startDateTime,omitempty"`
	EndDateTime   string                 `protobuf:"bytes,2,opt,name=endDateTime,proto3" json:"endDateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhysicalResourceResponse_ResourceRelationship_ValidFor) Reset() {
	*x = PhysicalResourceResponse_ResourceRelationship_ValidFor{}
	mi := &file_internal_proto_physicalResource_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalResourceResponse_ResourceRelationship_ValidFor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalResourceResponse_ResourceRelationship_ValidFor) ProtoMessage() {}

func (x *PhysicalResourceResponse_ResourceRelationship_ValidFor) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_physicalResource_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalResourceResponse_ResourceRelationship_ValidFor.ProtoReflect.Descriptor instead.
func (*PhysicalResourceResponse_ResourceRelationship_ValidFor) Descriptor() ([]byte, []int) {
	return file_internal_proto_physicalResource_proto_rawDescGZIP(), []int{1, 4, 0}
}

func (x *PhysicalResourceResponse_ResourceRelationship_ValidFor) GetStartDateTime() string {
	if x != nil {
		return x.StartDateTime
	}
	return ""
}

func (x *PhysicalResourceResponse_ResourceRelationship_ValidFor) GetEndDateTime() string {
	if x != nil {
		return x.EndDateTime
	}
	return ""
}

type PhysicalResourceResponse_ResourceRelationship_Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	BaseType      string                 `protobuf:"bytes,3,opt,name=baseType,proto3" json:"baseType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhysicalResourceResponse_ResourceRelationship_Resource) Reset() {
	*x = PhysicalResourceResponse_ResourceRelationship_Resource{}
	mi := &file_internal_proto_physicalResource_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalResourceResponse_ResourceRelationship_Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalResourceResponse_ResourceRelationship_Resource) ProtoMessage() {}

func (x *PhysicalResourceResponse_ResourceRelationship_Resource) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_physicalResource_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalResourceResponse_ResourceRelationship_Resource.ProtoReflect.Descriptor instead.
func (*PhysicalResourceResponse_ResourceRelationship_Resource) Descriptor() ([]byte, []int) {
	return file_internal_proto_physicalResource_proto_rawDescGZIP(), []int{1, 4, 1}
}

func (x *PhysicalResourceResponse_ResourceRelationship_Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PhysicalResourceResponse_ResourceRelationship_Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PhysicalResourceResponse_ResourceRelationship_Resource) GetBaseType() string {
	if x != nil {
		return x.BaseType
	}
	return ""
}

var File_internal_proto_physicalResource_proto protoreflect.FileDescriptor

const file_internal_proto_physicalResource_proto_rawDesc = "" +
	"\n" +
	"%internal/proto/physicalResource.proto\x12\x10physicalresource\"\xca\x11\n" +
	"\x10PhysicalResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1a\n" +
	"\bbaseType\x18\x05 \x01(\tR\bbaseType\x12\x1a\n" +
	"\bisBundle\x18\x06 \x01(\bR\bisBundle\x12\x14\n" +
	"\x05value\x18\a \x01(\tR\x05value\x12.\n" +
	"\x12startOperatingDate\x18\b \x01(\tR\x12startOperatingDate\x12*\n" +
	"\x10endOperatingDate\x18\t \x01(\tR\x10endOperatingDate\x120\n" +
	"\x13resourceRecycleDate\x18\n" +
	" \x01(\tR\x13resourceRecycleDate\x12&\n" +
	"\x0eresourceStatus\x18\v \x01(\tR\x0eresourceStatus\x12\"\n" +
	"\fbusinessType\x18\f \x03(\tR\fbusinessType\x12\x1a\n" +
	"\bcategory\x18\r \x03(\tR\bcategory\x12;\n" +
	"\x04cost\x18\x0e \x01(\v2'.physicalresource.PhysicalResource.CostR\x04cost\x12;\n" +
	"\x04note\x18\x0f \x03(\v2'.physicalresource.PhysicalResource.NoteR\x04note\x12S\n" +
	"\frelatedParty\x18\x10 \x03(\v2/.physicalresource.PhysicalResource.RelatedPartyR\frelatedParty\x12q\n" +
	"\x16resourceCharacteristic\x18\x11 \x03(\v29.physicalresource.PhysicalResource.ResourceCharacteristicR\x16resourceCharacteristic\x12k\n" +
	"\x14resourceRelationship\x18\x12 \x03(\v27.physicalresource.PhysicalResource.ResourceRelationshipR\x14resourceRelationship\x12_\n" +
	"\x10bundledResources\x18\x13 \x03(\v23.physicalresource.PhysicalResource.BundledResourcesR\x10bundledResources\x12\x1c\n" +
	"\tcreatedAt\x18\x14 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x15 \x01(\tR\tupdatedAt\x1a^\n" +
	"\x04Cost\x12\"\n" +
	"\ftaxFreeValue\x18\x01 \x01(\x03R\ftaxFreeValue\x12\x1e\n" +
	"\n" +
	"taxedValue\x18\x02 \x01(\x03R\n" +
	"taxedValue\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x1af\n" +
	"\x04Note\x12\x1e\n" +
	"\n" +
	"authorRole\x18\x01 \x01(\tR\n" +
	"authorRole\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x1af\n" +
	"\fRelatedParty\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bbaseType\x18\x04 \x01(\tR\bbaseType\x1a\xa0\x01\n" +
	"\x16ResourceCharacteristic\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x10publicIdentifier\x18\x03 \x01(\bR\x10publicIdentifier\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x1c\n" +
	"\tvalueType\x18\x05 \x01(\tR\tvalueType\x1a\x85\x04\n" +
	"\x14ResourceRelationship\x12*\n" +
	"\x10relationshipType\x18\x01 \x01(\tR\x10relationshipType\x12\\\n" +
	"\bvalidFor\x18\x02 \x01(\v2@.physicalresource.PhysicalResource.ResourceRelationship.ValidForR\bvalidFor\x12\\\n" +
	"\bresource\x18\x03 \x01(\v2@.physicalresource.PhysicalResource.ResourceRelationship.ResourceR\bresource\x1aR\n" +
	"\bValidFor\x12$\n" +
	"\rstartDateTime\x18\x01 \x01(\tR\rstartDateTime\x12 \n" +
	"\vendDateTime\x18\x02 \x01(\tR\vendDateTime\x1aJ\n" +
	"\bResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bbaseType\x18\x03 \x01(\tR\bbaseType\"e\n" +
	"\x10RelationshipType\x12\f\n" +
	"\breliesOn\x10\x00\x12\n" +
	"\n" +
	"\x06bundle\x10\x01\x12\x0e\n" +
	"\n" +
	"dependency\x10\x02\x12\x0f\n" +
	"\vstarterPack\x10\x03\x12\f\n" +
	"\bcapacity\x10\x04\x12\b\n" +
	"\x04pool\x10\x05\x1a\x8e\x01\n" +
	"\x10BundledResources\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04href\x18\x02 \x01(\tR\x04href\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bbaseType\x18\x04 \x01(\tR\bbaseType\x12&\n" +
	"\x0eschemaLocation\x18\x05 \x01(\tR\x0eschemaLocation\"`\n" +
	"\x0eResourceStatus\x12\v\n" +
	"\aCreated\x10\x00\x12\r\n" +
	"\tAvailable\x10\x01\x12\f\n" +
	"\bReserved\x10\x02\x12\t\n" +
	"\x05InUse\x10\x03\x12\v\n" +
	"\aRetired\x10\x04\x12\f\n" +
	"\bDisabled\x10\x05\"\x92\x12\n" +
	"\x18PhysicalResourceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1a\n" +
	"\bbaseType\x18\x05 \x01(\tR\bbaseType\x12\x1a\n" +
	"\bisBundle\x18\x06 \x01(\bR\bisBundle\x12\x14\n" +
	"\x05value\x18\a \x01(\tR\x05value\x12.\n" +
	"\x12startOperatingDate\x18\b \x01(\tR\x12startOperatingDate\x12*\n" +
	"\x10endOperatingDate\x18\t \x01(\tR\x10endOperatingDate\x120\n" +
	"\x13resourceRecycleDate\x18\n" +
	" \x01(\tR\x13resourceRecycleDate\x12&\n" +
	"\x0eresourceStatus\x18\v \x01(\tR\x0eresourceStatus\x12\"\n" +
	"\fbusinessType\x18\f \x03(\tR\fbusinessType\x12\x1a\n" +
	"\bcategory\x18\r \x03(\tR\bcategory\x12C\n" +
	"\x04cost\x18\x0e \x01(\v2/.physicalresource.PhysicalResourceResponse.CostR\x04cost\x12C\n" +
	"\x04note\x18\x0f \x03(\v2/.physicalresource.PhysicalResourceResponse.NoteR\x04note\x12[\n" +
	"\frelatedParty\x18\x10 \x03(\v27.physicalresource.PhysicalResourceResponse.RelatedPartyR\frelatedParty\x12y\n" +
	"\x16resourceCharacteristic\x18\x11 \x03(\v2A.physicalresource.PhysicalResourceResponse.ResourceCharacteristicR\x16resourceCharacteristic\x12s\n" +
	"\x14resourceRelationship\x18\x12 \x03(\v2?.physicalresource.PhysicalResourceResponse.ResourceRelationshipR\x14resourceRelationship\x12g\n" +
	"\x10bundledResources\x18\x13 \x03(\v2;.physicalresource.PhysicalResourceResponse.BundledResourcesR\x10bundledResources\x12\x1c\n" +
	"\tcreatedAt\x18\x14 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x15 \x01(\tR\tupdatedAt\x1a^\n" +
	"\x04Cost\x12\"\n" +
	"\ftaxFreeValue\x18\x01 \x01(\x03R\ftaxFreeValue\x12\x1e\n" +
	"\n" +
	"taxedValue\x18\x02 \x01(\x03R\n" +
	"taxedValue\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x1af\n" +
	"\x04Note\x12\x1e\n" +
	"\n" +
	"authorRole\x18\x01 \x01(\tR\n" +
	"authorRole\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x1af\n" +
	"\fRelatedParty\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bbaseType\x18\x04 \x01(\tR\bbaseType\x1a\xa0\x01\n" +
	"\x16ResourceCharacteristic\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x10publicIdentifier\x18\x03 \x01(\bR\x10publicIdentifier\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x1c\n" +
	"\tvalueType\x18\x05 \x01(\tR\tvalueType\x1a\x95\x04\n" +
	"\x14ResourceRelationship\x12*\n" +
	"\x10relationshipType\x18\x01 \x01(\tR\x10relationshipType\x12d\n" +
	"\bvalidFor\x18\x02 \x01(\v2H.physicalresource.PhysicalResourceResponse.ResourceRelationship.ValidForR\bvalidFor\x12d\n" +
	"\bresource\x18\x03 \x01(\v2H.physicalresource.PhysicalResourceResponse.ResourceRelationship.ResourceR\bresource\x1aR\n" +
	"\bValidFor\x12$\n" +
	"\rstartDateTime\x18\x01 \x01(\tR\rstartDateTime\x12 \n" +
	"\vendDateTime\x18\x02 \x01(\tR\vendDateTime\x1aJ\n" +
	"\bResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bbaseType\x18\x03 \x01(\tR\bbaseType\"e\n" +
	"\x10RelationshipType\x12\f\n" +
	"\breliesOn\x10\x00\x12\n" +
	"\n" +
	"\x06bundle\x10\x01\x12\x0e\n" +
	"\n" +
	"dependency\x10\x02\x12\x0f\n" +
	"\vstarterPack\x10\x03\x12\f\n" +
	"\bcapacity\x10\x04\x12\b\n" +
	"\x04pool\x10\x05\x1a\x8e\x01\n" +
	"\x10BundledResources\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04href\x18\x02 \x01(\tR\x04href\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bbaseType\x18\x04 \x01(\tR\bbaseType\x12&\n" +
	"\x0eschemaLocation\x18\x05 \x01(\tR\x0eschemaLocation\"`\n" +
	"\x0eResourceStatus\x12\v\n" +
	"\aCreated\x10\x00\x12\r\n" +
	"\tAvailable\x10\x01\x12\f\n" +
	"\bReserved\x10\x02\x12\t\n" +
	"\x05InUse\x10\x03\x12\v\n" +
	"\aRetired\x10\x04\x12\f\n" +
	"\bDisabled\x10\x05\"v\n" +
	"\x14PatchPhysicalRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12N\n" +
	"\x10physicalResource\x18\x02 \x01(\v2\".physicalresource.PhysicalResourceR\x10physicalResource2\xf0\x01\n" +
	"\x17PhysicalResourceService\x12h\n" +
	"\x16CreatePhysicalResource\x12\".physicalresource.PhysicalResource\x1a*.physicalresource.PhysicalResourceResponse\x12k\n" +
	"\x15PatchPhysicalResource\x12&.physicalresource.PatchPhysicalRequest\x1a*.physicalresource.PhysicalResourceResponseBCZAdrm-bulk-service/internal/proto/physicalresource;physicalresourceb\x06proto3"

var (
	file_internal_proto_physicalResource_proto_rawDescOnce sync.Once
	file_internal_proto_physicalResource_proto_rawDescData []byte
)

func file_internal_proto_physicalResource_proto_rawDescGZIP() []byte {
	file_internal_proto_physicalResource_proto_rawDescOnce.Do(func() {
		file_internal_proto_physicalResource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_physicalResource_proto_rawDesc), len(file_internal_proto_physicalResource_proto_rawDesc)))
	})
	return file_internal_proto_physicalResource_proto_rawDescData
}

var file_internal_proto_physicalResource_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_internal_proto_physicalResource_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_internal_proto_physicalResource_proto_goTypes = []any{
	(PhysicalResource_ResourceStatus)(0),                                // 0: physicalresource.PhysicalResource.ResourceStatus
	(PhysicalResource_ResourceRelationship_RelationshipType)(0),         // 1: physicalresource.PhysicalResource.ResourceRelationship.RelationshipType
	(PhysicalResourceResponse_ResourceStatus)(0),                        // 2: physicalresource.PhysicalResourceResponse.ResourceStatus
	(PhysicalResourceResponse_ResourceRelationship_RelationshipType)(0), // 3: physicalresource.PhysicalResourceResponse.ResourceRelationship.RelationshipType
	(*PhysicalResource)(nil),                                            // 4: physicalresource.PhysicalResource
	(*PhysicalResourceResponse)(nil),                                    // 5: physicalresource.PhysicalResourceResponse
	(*PatchPhysicalRequest)(nil),                                        // 6: physicalresource.PatchPhysicalRequest
	(*PhysicalResource_Cost)(nil),                                       // 7: physicalresource.PhysicalResource.Cost
	(*PhysicalResource_Note)(nil),                                       // 8: physicalresource.PhysicalResource.Note
	(*PhysicalResource_RelatedParty)(nil),                               // 9: physicalresource.PhysicalResource.RelatedParty
	(*PhysicalResource_ResourceCharacteristic)(nil),                     // 10: physicalresource.PhysicalResource.ResourceCharacteristic
	(*PhysicalResource_ResourceRelationship)(nil),                       // 11: physicalresource.PhysicalResource.ResourceRelationship
	(*PhysicalResource_BundledResources)(nil),                           // 12: physicalresource.PhysicalResource.BundledResources
	(*PhysicalResource_ResourceRelationship_ValidFor)(nil),              // 13: physicalresource.PhysicalResource.ResourceRelationship.ValidFor
	(*PhysicalResource_ResourceRelationship_Resource)(nil),              // 14: physicalresource.PhysicalResource.ResourceRelationship.Resource
	(*PhysicalResourceResponse_Cost)(nil),                               // 15: physicalresource.PhysicalResourceResponse.Cost
	(*PhysicalResourceResponse_Note)(nil),                               // 16: physicalresource.PhysicalResourceResponse.Note
	(*PhysicalResourceResponse_RelatedParty)(nil),                       // 17: physicalresource.PhysicalResourceResponse.RelatedParty
	(*PhysicalResourceResponse_ResourceCharacteristic)(nil),             // 18: physicalresource.PhysicalResourceResponse.ResourceCharacteristic
	(*PhysicalResourceResponse_ResourceRelationship)(nil),               // 19: physicalresource.PhysicalResourceResponse.ResourceRelationship
	(*PhysicalResourceResponse_BundledResources)(nil),                   // 20: physicalresource.PhysicalResourceResponse.BundledResources
	(*PhysicalResourceResponse_ResourceRelationship_ValidFor)(nil),      // 21: physicalresource.PhysicalResourceResponse.ResourceRelationship.ValidFor
	(*PhysicalResourceResponse_ResourceRelationship_Resource)(nil),      // 22: physicalresource.PhysicalResourceResponse.ResourceRelationship.Resource
}
var file_internal_proto_physicalResource_proto_depIdxs = []int32{
	7,  // 0: physicalresource.PhysicalResource.cost:type_name -> physicalresource.PhysicalResource.Cost
	8,  // 1: physicalresource.PhysicalResource.note:type_name -> physicalresource.PhysicalResource.Note
	9,  // 2: physicalresource.PhysicalResource.relatedParty:type_name -> physicalresource.PhysicalResource.RelatedParty
	10, // 3: physicalresource.PhysicalResource.resourceCharacteristic:type_name -> physicalresource.PhysicalResource.ResourceCharacteristic
	11, // 4: physicalresource.PhysicalResource.resourceRelationship:type_name -> physicalresource.PhysicalResource.ResourceRelationship
	12, // 5: physicalresource.PhysicalResource.bundledResources:type_name -> physicalresource.PhysicalResource.BundledResources
	15, // 6: physicalresource.PhysicalResourceResponse.cost:type_name -> physicalresource.PhysicalResourceResponse.Cost
	16, // 7: physicalresource.PhysicalResourceResponse.note:type_name -> physicalresource.PhysicalResourceResponse.Note
	17, // 8: physicalresource.PhysicalResourceResponse.relatedParty:type_name -> physicalresource.PhysicalResourceResponse.RelatedParty
	18, // 9: physicalresource.PhysicalResourceResponse.resourceCharacteristic:type_name -> physicalresource.PhysicalResourceResponse.ResourceCharacteristic
	19, // 10: physicalresource.PhysicalResourceResponse.resourceRelationship:type_name -> physicalresource.PhysicalResourceResponse.ResourceRelationship
	20, // 11: physicalresource.PhysicalResourceResponse.bundledResources:type_name -> physicalresource.PhysicalResourceResponse.BundledResources
	4,  // 12: physicalresource.PatchPhysicalRequest.physicalResource:type_name -> physicalresource.PhysicalResource
	13, // 13: physicalresource.PhysicalResource.ResourceRelationship.validFor:type_name -> physicalresource.PhysicalResource.ResourceRelationship.ValidFor
	14, // 14: physicalresource.PhysicalResource.ResourceRelationship.resource:type_name -> physicalresource.PhysicalResource.ResourceRelationship.Resource
	21, // 15: physicalresource.PhysicalResourceResponse.ResourceRelationship.validFor:type_name -> physicalresource.PhysicalResourceResponse.ResourceRelationship.ValidFor
	22, // 16: physicalresource.PhysicalResourceResponse.ResourceRelationship.resource:type_name -> physicalresource.PhysicalResourceResponse.ResourceRelationship.Resource
	4,  // 17: physicalresource.PhysicalResourceService.CreatePhysicalResource:input_type -> physicalresource.PhysicalResource
	6,  // 18: physicalresource.PhysicalResourceService.PatchPhysicalResource:input_type -> physicalresource.PatchPhysicalRequest
	5,  // 19: physicalresource.PhysicalResourceService.CreatePhysicalResource:output_type -> physicalresource.PhysicalResourceResponse
	5,  // 20: physicalresource.PhysicalResourceService.PatchPhysicalResource:output_type -> physicalresource.PhysicalResourceResponse
	19, // [19:21] is the sub-list for method output_type
	17, // [17:19] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_internal_proto_physicalResource_proto_init() }
func file_internal_proto_physicalResource_proto_init() {
	if File_internal_proto_physicalResource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_physicalResource_proto_rawDesc), len(file_internal_proto_physicalResource_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_physicalResource_proto_goTypes,
		DependencyIndexes: file_internal_proto_physicalResource_proto_depIdxs,
		EnumInfos:         file_internal_proto_physicalResource_proto_enumTypes,
		MessageInfos:      file_internal_proto_physicalResource_proto_msgTypes,
	}.Build()
	File_internal_proto_physicalResource_proto = out.File
	file_internal_proto_physicalResource_proto_goTypes = nil
	file_internal_proto_physicalResource_proto_depIdxs = nil
}
