// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.3
// source: internal/proto/physicalResource.proto

package physicalresource

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PhysicalResourceService_CreatePhysicalResource_FullMethodName = "/physicalresource.PhysicalResourceService/CreatePhysicalResource"
	PhysicalResourceService_PatchPhysicalResource_FullMethodName  = "/physicalresource.PhysicalResourceService/PatchPhysicalResource"
)

// PhysicalResourceServiceClient is the client API for PhysicalResourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PhysicalResourceServiceClient interface {
	CreatePhysicalResource(ctx context.Context, in *PhysicalResource, opts ...grpc.CallOption) (*PhysicalResourceResponse, error)
	PatchPhysicalResource(ctx context.Context, in *PatchPhysicalRequest, opts ...grpc.CallOption) (*PhysicalResourceResponse, error)
}

type physicalResourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPhysicalResourceServiceClient(cc grpc.ClientConnInterface) PhysicalResourceServiceClient {
	return &physicalResourceServiceClient{cc}
}

func (c *physicalResourceServiceClient) CreatePhysicalResource(ctx context.Context, in *PhysicalResource, opts ...grpc.CallOption) (*PhysicalResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PhysicalResourceResponse)
	err := c.cc.Invoke(ctx, PhysicalResourceService_CreatePhysicalResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *physicalResourceServiceClient) PatchPhysicalResource(ctx context.Context, in *PatchPhysicalRequest, opts ...grpc.CallOption) (*PhysicalResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PhysicalResourceResponse)
	err := c.cc.Invoke(ctx, PhysicalResourceService_PatchPhysicalResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PhysicalResourceServiceServer is the server API for PhysicalResourceService service.
// All implementations must embed UnimplementedPhysicalResourceServiceServer
// for forward compatibility.
type PhysicalResourceServiceServer interface {
	CreatePhysicalResource(context.Context, *PhysicalResource) (*PhysicalResourceResponse, error)
	PatchPhysicalResource(context.Context, *PatchPhysicalRequest) (*PhysicalResourceResponse, error)
	mustEmbedUnimplementedPhysicalResourceServiceServer()
}

// UnimplementedPhysicalResourceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPhysicalResourceServiceServer struct{}

func (UnimplementedPhysicalResourceServiceServer) CreatePhysicalResource(context.Context, *PhysicalResource) (*PhysicalResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePhysicalResource not implemented")
}
func (UnimplementedPhysicalResourceServiceServer) PatchPhysicalResource(context.Context, *PatchPhysicalRequest) (*PhysicalResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PatchPhysicalResource not implemented")
}
func (UnimplementedPhysicalResourceServiceServer) mustEmbedUnimplementedPhysicalResourceServiceServer() {
}
func (UnimplementedPhysicalResourceServiceServer) testEmbeddedByValue() {}

// UnsafePhysicalResourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PhysicalResourceServiceServer will
// result in compilation errors.
type UnsafePhysicalResourceServiceServer interface {
	mustEmbedUnimplementedPhysicalResourceServiceServer()
}

func RegisterPhysicalResourceServiceServer(s grpc.ServiceRegistrar, srv PhysicalResourceServiceServer) {
	// If the following call panics, it indicates UnimplementedPhysicalResourceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PhysicalResourceService_ServiceDesc, srv)
}

func _PhysicalResourceService_CreatePhysicalResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhysicalResource)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhysicalResourceServiceServer).CreatePhysicalResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhysicalResourceService_CreatePhysicalResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhysicalResourceServiceServer).CreatePhysicalResource(ctx, req.(*PhysicalResource))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhysicalResourceService_PatchPhysicalResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchPhysicalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhysicalResourceServiceServer).PatchPhysicalResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhysicalResourceService_PatchPhysicalResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhysicalResourceServiceServer).PatchPhysicalResource(ctx, req.(*PatchPhysicalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PhysicalResourceService_ServiceDesc is the grpc.ServiceDesc for PhysicalResourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PhysicalResourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "physicalresource.PhysicalResourceService",
	HandlerType: (*PhysicalResourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePhysicalResource",
			Handler:    _PhysicalResourceService_CreatePhysicalResource_Handler,
		},
		{
			MethodName: "PatchPhysicalResource",
			Handler:    _PhysicalResourceService_PatchPhysicalResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/physicalResource.proto",
}
