// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: internal/proto/logicalResource.proto

package logicalresource

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogicalResource_ResourceStatus int32

const (
	LogicalResource_Created   LogicalResource_ResourceStatus = 0
	LogicalResource_Available LogicalResource_ResourceStatus = 1
	LogicalResource_Reserved  LogicalResource_ResourceStatus = 2
	LogicalResource_InUse     LogicalResource_ResourceStatus = 3
	LogicalResource_Retired   LogicalResource_ResourceStatus = 4
	LogicalResource_Disabled  LogicalResource_ResourceStatus = 5
)

// Enum value maps for LogicalResource_ResourceStatus.
var (
	LogicalResource_ResourceStatus_name = map[int32]string{
		0: "Created",
		1: "Available",
		2: "Reserved",
		3: "InUse",
		4: "Retired",
		5: "Disabled",
	}
	LogicalResource_ResourceStatus_value = map[string]int32{
		"Created":   0,
		"Available": 1,
		"Reserved":  2,
		"InUse":     3,
		"Retired":   4,
		"Disabled":  5,
	}
)

func (x LogicalResource_ResourceStatus) Enum() *LogicalResource_ResourceStatus {
	p := new(LogicalResource_ResourceStatus)
	*p = x
	return p
}

func (x LogicalResource_ResourceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogicalResource_ResourceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_logicalResource_proto_enumTypes[0].Descriptor()
}

func (LogicalResource_ResourceStatus) Type() protoreflect.EnumType {
	return &file_internal_proto_logicalResource_proto_enumTypes[0]
}

func (x LogicalResource_ResourceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogicalResource_ResourceStatus.Descriptor instead.
func (LogicalResource_ResourceStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_logicalResource_proto_rawDescGZIP(), []int{0, 0}
}

type LogicalResource_ResourceRelationship_RelationshipType int32

const (
	LogicalResource_ResourceRelationship_reliesOn    LogicalResource_ResourceRelationship_RelationshipType = 0
	LogicalResource_ResourceRelationship_bundle      LogicalResource_ResourceRelationship_RelationshipType = 1
	LogicalResource_ResourceRelationship_dependency  LogicalResource_ResourceRelationship_RelationshipType = 2
	LogicalResource_ResourceRelationship_starterPack LogicalResource_ResourceRelationship_RelationshipType = 3
	LogicalResource_ResourceRelationship_capacity    LogicalResource_ResourceRelationship_RelationshipType = 4
	LogicalResource_ResourceRelationship_pool        LogicalResource_ResourceRelationship_RelationshipType = 5
)

// Enum value maps for LogicalResource_ResourceRelationship_RelationshipType.
var (
	LogicalResource_ResourceRelationship_RelationshipType_name = map[int32]string{
		0: "reliesOn",
		1: "bundle",
		2: "dependency",
		3: "starterPack",
		4: "capacity",
		5: "pool",
	}
	LogicalResource_ResourceRelationship_RelationshipType_value = map[string]int32{
		"reliesOn":    0,
		"bundle":      1,
		"dependency":  2,
		"starterPack": 3,
		"capacity":    4,
		"pool":        5,
	}
)

func (x LogicalResource_ResourceRelationship_RelationshipType) Enum() *LogicalResource_ResourceRelationship_RelationshipType {
	p := new(LogicalResource_ResourceRelationship_RelationshipType)
	*p = x
	return p
}

func (x LogicalResource_ResourceRelationship_RelationshipType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogicalResource_ResourceRelationship_RelationshipType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_logicalResource_proto_enumTypes[1].Descriptor()
}

func (LogicalResource_ResourceRelationship_RelationshipType) Type() protoreflect.EnumType {
	return &file_internal_proto_logicalResource_proto_enumTypes[1]
}

func (x LogicalResource_ResourceRelationship_RelationshipType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogicalResource_ResourceRelationship_RelationshipType.Descriptor instead.
func (LogicalResource_ResourceRelationship_RelationshipType) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_logicalResource_proto_rawDescGZIP(), []int{0, 4, 0}
}

type LogicalResourceResponse_ResourceStatus int32

const (
	LogicalResourceResponse_Created   LogicalResourceResponse_ResourceStatus = 0
	LogicalResourceResponse_Available LogicalResourceResponse_ResourceStatus = 1
	LogicalResourceResponse_Reserved  LogicalResourceResponse_ResourceStatus = 2
	LogicalResourceResponse_InUse     LogicalResourceResponse_ResourceStatus = 3
	LogicalResourceResponse_Retired   LogicalResourceResponse_ResourceStatus = 4
	LogicalResourceResponse_Disabled  LogicalResourceResponse_ResourceStatus = 5
)

// Enum value maps for LogicalResourceResponse_ResourceStatus.
var (
	LogicalResourceResponse_ResourceStatus_name = map[int32]string{
		0: "Created",
		1: "Available",
		2: "Reserved",
		3: "InUse",
		4: "Retired",
		5: "Disabled",
	}
	LogicalResourceResponse_ResourceStatus_value = map[string]int32{
		"Created":   0,
		"Available": 1,
		"Reserved":  2,
		"InUse":     3,
		"Retired":   4,
		"Disabled":  5,
	}
)

func (x LogicalResourceResponse_ResourceStatus) Enum() *LogicalResourceResponse_ResourceStatus {
	p := new(LogicalResourceResponse_ResourceStatus)
	*p = x
	return p
}

func (x LogicalResourceResponse_ResourceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogicalResourceResponse_ResourceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_logicalResource_proto_enumTypes[2].Descriptor()
}

func (LogicalResourceResponse_ResourceStatus) Type() protoreflect.EnumType {
	return &file_internal_proto_logicalResource_proto_enumTypes[2]
}

func (x LogicalResourceResponse_ResourceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogicalResourceResponse_ResourceStatus.Descriptor instead.
func (LogicalResourceResponse_ResourceStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_logicalResource_proto_rawDescGZIP(), []int{1, 0}
}

type LogicalResourceResponse_ResourceRelationship_RelationshipType int32

const (
	LogicalResourceResponse_ResourceRelationship_reliesOn    LogicalResourceResponse_ResourceRelationship_RelationshipType = 0
	LogicalResourceResponse_ResourceRelationship_bundle      LogicalResourceResponse_ResourceRelationship_RelationshipType = 1
	LogicalResourceResponse_ResourceRelationship_dependency  LogicalResourceResponse_ResourceRelationship_RelationshipType = 2
	LogicalResourceResponse_ResourceRelationship_starterPack LogicalResourceResponse_ResourceRelationship_RelationshipType = 3
	LogicalResourceResponse_ResourceRelationship_capacity    LogicalResourceResponse_ResourceRelationship_RelationshipType = 4
	LogicalResourceResponse_ResourceRelationship_pool        LogicalResourceResponse_ResourceRelationship_RelationshipType = 5
)

// Enum value maps for LogicalResourceResponse_ResourceRelationship_RelationshipType.
var (
	LogicalResourceResponse_ResourceRelationship_RelationshipType_name = map[int32]string{
		0: "reliesOn",
		1: "bundle",
		2: "dependency",
		3: "starterPack",
		4: "capacity",
		5: "pool",
	}
	LogicalResourceResponse_ResourceRelationship_RelationshipType_value = map[string]int32{
		"reliesOn":    0,
		"bundle":      1,
		"dependency":  2,
		"starterPack": 3,
		"capacity":    4,
		"pool":        5,
	}
)

func (x LogicalResourceResponse_ResourceRelationship_RelationshipType) Enum() *LogicalResourceResponse_ResourceRelationship_RelationshipType {
	p := new(LogicalResourceResponse_ResourceRelationship_RelationshipType)
	*p = x
	return p
}

func (x LogicalResourceResponse_ResourceRelationship_RelationshipType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogicalResourceResponse_ResourceRelationship_RelationshipType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_logicalResource_proto_enumTypes[3].Descriptor()
}

func (LogicalResourceResponse_ResourceRelationship_RelationshipType) Type() protoreflect.EnumType {
	return &file_internal_proto_logicalResource_proto_enumTypes[3]
}

func (x LogicalResourceResponse_ResourceRelationship_RelationshipType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogicalResourceResponse_ResourceRelationship_RelationshipType.Descriptor instead.
func (LogicalResourceResponse_ResourceRelationship_RelationshipType) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_logicalResource_proto_rawDescGZIP(), []int{1, 4, 0}
}

type LogicalResource struct {
	state                  protoimpl.MessageState                    `protogen:"open.v1"`
	Id                     string                                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description            string                                    `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Name                   string                                    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type                   string                                    `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	BaseType               string                                    `protobuf:"bytes,5,opt,name=baseType,proto3" json:"baseType,omitempty"`
	IsBundle               bool                                      `protobuf:"varint,6,opt,name=isBundle,proto3" json:"isBundle,omitempty"`
	Value                  string                                    `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	StartOperatingDate     string                                    `protobuf:"bytes,8,opt,name=startOperatingDate,proto3" json:"startOperatingDate,omitempty"`
	EndOperatingDate       string                                    `protobuf:"bytes,9,opt,name=endOperatingDate,proto3" json:"endOperatingDate,omitempty"`
	ResourceRecycleDate    string                                    `protobuf:"bytes,10,opt,name=resourceRecycleDate,proto3" json:"resourceRecycleDate,omitempty"`
	ResourceStatus         string                                    `protobuf:"bytes,11,opt,name=resourceStatus,proto3" json:"resourceStatus,omitempty"`
	BusinessType           []string                                  `protobuf:"bytes,12,rep,name=businessType,proto3" json:"businessType,omitempty"`
	Category               []string                                  `protobuf:"bytes,13,rep,name=category,proto3" json:"category,omitempty"`
	Cost                   *LogicalResource_Cost                     `protobuf:"bytes,14,opt,name=cost,proto3" json:"cost,omitempty"`
	Note                   []*LogicalResource_Note                   `protobuf:"bytes,15,rep,name=note,proto3" json:"note,omitempty"`
	RelatedParty           []*LogicalResource_RelatedParty           `protobuf:"bytes,16,rep,name=relatedParty,proto3" json:"relatedParty,omitempty"`
	ResourceCharacteristic []*LogicalResource_ResourceCharacteristic `protobuf:"bytes,17,rep,name=resourceCharacteristic,proto3" json:"resourceCharacteristic,omitempty"`
	ResourceRelationship   []*LogicalResource_ResourceRelationship   `protobuf:"bytes,18,rep,name=resourceRelationship,proto3" json:"resourceRelationship,omitempty"`
	BundledResources       []*LogicalResource_BundledResources       `protobuf:"bytes,19,rep,name=bundledResources,proto3" json:"bundledResources,omitempty"`
	CreatedAt              string                                    `protobuf:"bytes,20,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt              string                                    `protobuf:"bytes,21,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LogicalResource) Reset() {
	*x = LogicalResource{}
	mi := &file_internal_proto_logicalResource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalResource) ProtoMessage() {}

func (x *LogicalResource) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logicalResource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalResource.ProtoReflect.Descriptor instead.
func (*LogicalResource) Descriptor() ([]byte, []int) {
	return file_internal_proto_logicalResource_proto_rawDescGZIP(), []int{0}
}

func (x *LogicalResource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogicalResource) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LogicalResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LogicalResource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LogicalResource) GetBaseType() string {
	if x != nil {
		return x.BaseType
	}
	return ""
}

func (x *LogicalResource) GetIsBundle() bool {
	if x != nil {
		return x.IsBundle
	}
	return false
}

func (x *LogicalResource) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *LogicalResource) GetStartOperatingDate() string {
	if x != nil {
		return x.StartOperatingDate
	}
	return ""
}

func (x *LogicalResource) GetEndOperatingDate() string {
	if x != nil {
		return x.EndOperatingDate
	}
	return ""
}

func (x *LogicalResource) GetResourceRecycleDate() string {
	if x != nil {
		return x.ResourceRecycleDate
	}
	return ""
}

func (x *LogicalResource) GetResourceStatus() string {
	if x != nil {
		return x.ResourceStatus
	}
	return ""
}

func (x *LogicalResource) GetBusinessType() []string {
	if x != nil {
		return x.BusinessType
	}
	return nil
}

func (x *LogicalResource) GetCategory() []string {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *LogicalResource) GetCost() *LogicalResource_Cost {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *LogicalResource) GetNote() []*LogicalResource_Note {
	if x != nil {
		return x.Note
	}
	return nil
}

func (x *LogicalResource) GetRelatedParty() []*LogicalResource_RelatedParty {
	if x != nil {
		return x.RelatedParty
	}
	return nil
}

func (x *LogicalResource) GetResourceCharacteristic() []*LogicalResource_ResourceCharacteristic {
	if x != nil {
		return x.ResourceCharacteristic
	}
	return nil
}

func (x *LogicalResource) GetResourceRelationship() []*LogicalResource_ResourceRelationship {
	if x != nil {
		return x.ResourceRelationship
	}
	return nil
}

func (x *LogicalResource) GetBundledResources() []*LogicalResource_BundledResources {
	if x != nil {
		return x.BundledResources
	}
	return nil
}

func (x *LogicalResource) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *LogicalResource) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type LogicalResourceResponse struct {
	state                  protoimpl.MessageState                            `protogen:"open.v1"`
	Id                     string                                            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description            string                                            `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Name                   string                                            `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type                   string                                            `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	BaseType               string                                            `protobuf:"bytes,5,opt,name=baseType,proto3" json:"baseType,omitempty"`
	IsBundle               bool                                              `protobuf:"varint,6,opt,name=isBundle,proto3" json:"isBundle,omitempty"`
	Value                  string                                            `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	StartOperatingDate     string                                            `protobuf:"bytes,8,opt,name=startOperatingDate,proto3" json:"startOperatingDate,omitempty"`
	EndOperatingDate       string                                            `protobuf:"bytes,9,opt,name=endOperatingDate,proto3" json:"endOperatingDate,omitempty"`
	ResourceRecycleDate    string                                            `protobuf:"bytes,10,opt,name=resourceRecycleDate,proto3" json:"resourceRecycleDate,omitempty"`
	ResourceStatus         string                                            `protobuf:"bytes,11,opt,name=resourceStatus,proto3" json:"resourceStatus,omitempty"`
	BusinessType           []string                                          `protobuf:"bytes,12,rep,name=businessType,proto3" json:"businessType,omitempty"`
	Category               []string                                          `protobuf:"bytes,13,rep,name=category,proto3" json:"category,omitempty"`
	Cost                   *LogicalResourceResponse_Cost                     `protobuf:"bytes,14,opt,name=cost,proto3" json:"cost,omitempty"`
	Note                   []*LogicalResourceResponse_Note                   `protobuf:"bytes,15,rep,name=note,proto3" json:"note,omitempty"`
	RelatedParty           []*LogicalResourceResponse_RelatedParty           `protobuf:"bytes,16,rep,name=relatedParty,proto3" json:"relatedParty,omitempty"`
	ResourceCharacteristic []*LogicalResourceResponse_ResourceCharacteristic `protobuf:"bytes,17,rep,name=resourceCharacteristic,proto3" json:"resourceCharacteristic,omitempty"`
	ResourceRelationship   []*LogicalResourceResponse_ResourceRelationship   `protobuf:"bytes,18,rep,name=resourceRelationship,proto3" json:"resourceRelationship,omitempty"`
	BundledResources       []*LogicalResourceResponse_BundledResources       `protobuf:"bytes,19,rep,name=bundledResources,proto3" json:"bundledResources,omitempty"`
	CreatedAt              string                                            `protobuf:"bytes,20,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt              string                                            `protobuf:"bytes,21,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LogicalResourceResponse) Reset() {
	*x = LogicalResourceResponse{}
	mi := &file_internal_proto_logicalResource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalResourceResponse) ProtoMessage() {}

func (x *LogicalResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logicalResource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalResourceResponse.ProtoReflect.Descriptor instead.
func (*LogicalResourceResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_logicalResource_proto_rawDescGZIP(), []int{1}
}

func (x *LogicalResourceResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogicalResourceResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LogicalResourceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LogicalResourceResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LogicalResourceResponse) GetBaseType() string {
	if x != nil {
		return x.BaseType
	}
	return ""
}

func (x *LogicalResourceResponse) GetIsBundle() bool {
	if x != nil {
		return x.IsBundle
	}
	return false
}

func (x *LogicalResourceResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *LogicalResourceResponse) GetStartOperatingDate() string {
	if x != nil {
		return x.StartOperatingDate
	}
	return ""
}

func (x *LogicalResourceResponse) GetEndOperatingDate() string {
	if x != nil {
		return x.EndOperatingDate
	}
	return ""
}

func (x *LogicalResourceResponse) GetResourceRecycleDate() string {
	if x != nil {
		return x.ResourceRecycleDate
	}
	return ""
}

func (x *LogicalResourceResponse) GetResourceStatus() string {
	if x != nil {
		return x.ResourceStatus
	}
	return ""
}

func (x *LogicalResourceResponse) GetBusinessType() []string {
	if x != nil {
		return x.BusinessType
	}
	return nil
}

func (x *LogicalResourceResponse) GetCategory() []string {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *LogicalResourceResponse) GetCost() *LogicalResourceResponse_Cost {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *LogicalResourceResponse) GetNote() []*LogicalResourceResponse_Note {
	if x != nil {
		return x.Note
	}
	return nil
}

func (x *LogicalResourceResponse) GetRelatedParty() []*LogicalResourceResponse_RelatedParty {
	if x != nil {
		return x.RelatedParty
	}
	return nil
}

func (x *LogicalResourceResponse) GetResourceCharacteristic() []*LogicalResourceResponse_ResourceCharacteristic {
	if x != nil {
		return x.ResourceCharacteristic
	}
	return nil
}

func (x *LogicalResourceResponse) GetResourceRelationship() []*LogicalResourceResponse_ResourceRelationship {
	if x != nil {
		return x.ResourceRelationship
	}
	return nil
}

func (x *LogicalResourceResponse) GetBundledResources() []*LogicalResourceResponse_BundledResources {
	if x != nil {
		return x.BundledResources
	}
	return nil
}

func (x *LogicalResourceResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *LogicalResourceResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type PatchLogicalRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LogicalResource *LogicalResource       `protobuf:"bytes,2,opt,name=logicalResource,proto3" json:"logicalResource,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PatchLogicalRequest) Reset() {
	*x = PatchLogicalRequest{}
	mi := &file_internal_proto_logicalResource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchLogicalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchLogicalRequest) ProtoMessage() {}

func (x *PatchLogicalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logicalResource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchLogicalRequest.ProtoReflect.Descriptor instead.
func (*PatchLogicalRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_logicalResource_proto_rawDescGZIP(), []int{2}
}

func (x *PatchLogicalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PatchLogicalRequest) GetLogicalResource() *LogicalResource {
	if x != nil {
		return x.LogicalResource
	}
	return nil
}

type LogicalResource_Cost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaxFreeValue  int64                  `protobuf:"varint,1,opt,name=taxFreeValue,proto3" json:"taxFreeValue,omitempty"`
	TaxedValue    int64                  `protobuf:"varint,2,opt,name=taxedValue,proto3" json:"taxedValue,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogicalResource_Cost) Reset() {
	*x = LogicalResource_Cost{}
	mi := &file_internal_proto_logicalResource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalResource_Cost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalResource_Cost) ProtoMessage() {}

func (x *LogicalResource_Cost) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logicalResource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalResource_Cost.ProtoReflect.Descriptor instead.
func (*LogicalResource_Cost) Descriptor() ([]byte, []int) {
	return file_internal_proto_logicalResource_proto_rawDescGZIP(), []int{0, 0}
}

func (x *LogicalResource_Cost) GetTaxFreeValue() int64 {
	if x != nil {
		return x.TaxFreeValue
	}
	return 0
}

func (x *LogicalResource_Cost) GetTaxedValue() int64 {
	if x != nil {
		return x.TaxedValue
	}
	return 0
}

func (x *LogicalResource_Cost) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type LogicalResource_Note struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorRole    string                 `protobuf:"bytes,1,opt,name=authorRole,proto3" json:"authorRole,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"` // ISO date string
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogicalResource_Note) Reset() {
	*x = LogicalResource_Note{}
	mi := &file_internal_proto_logicalResource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalResource_Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalResource_Note) ProtoMessage() {}

func (x *LogicalResource_Note) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logicalResource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalResource_Note.ProtoReflect.Descriptor instead.
func (*LogicalResource_Note) Descriptor() ([]byte, []int) {
	return file_internal_proto_logicalResource_proto_rawDescGZIP(), []int{0, 1}
}

func (x *LogicalResource_Note) GetAuthorRole() string {
	if x != nil {
		return x.AuthorRole
	}
	return ""
}

func (x *LogicalResource_Note) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *LogicalResource_Note) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *LogicalResource_Note) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type LogicalResource_RelatedParty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	BaseType      string                 `protobuf:"bytes,4,opt,name=baseType,proto3" json:"baseType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogicalResource_RelatedParty) Reset() {
	*x = LogicalResource_RelatedParty{}
	mi := &file_internal_proto_logicalResource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalResource_RelatedParty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalResource_RelatedParty) ProtoMessage() {}

func (x *LogicalResource_RelatedParty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logicalResource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalResource_RelatedParty.ProtoReflect.Descriptor instead.
func (*LogicalResource_RelatedParty) Descriptor() ([]byte, []int) {
	return file_internal_proto_logicalResource_proto_rawDescGZIP(), []int{0, 2}
}

func (x *LogicalResource_RelatedParty) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LogicalResource_RelatedParty) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *LogicalResource_RelatedParty) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LogicalResource_RelatedParty) GetBaseType() string {
	if x != nil {
		return x.BaseType
	}
	return ""
}

type LogicalResource_ResourceCharacteristic struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Code             string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PublicIdentifier bool                   `protobuf:"varint,3,opt,name=publicIdentifier,proto3" json:"publicIdentifier,omitempty"`
	Value            string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	ValueType        string                 `protobuf:"bytes,5,opt,name=valueType,proto3" json:"valueType,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LogicalResource_ResourceCharacteristic) Reset() {
	*x = LogicalResource_ResourceCharacteristic{}
	mi := &file_internal_proto_logicalResource_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalResource_ResourceCharacteristic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalResource_ResourceCharacteristic) ProtoMessage() {}

func (x *LogicalResource_ResourceCharacteristic) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logicalResource_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalResource_ResourceCharacteristic.ProtoReflect.Descriptor instead.
func (*LogicalResource_ResourceCharacteristic) Descriptor() ([]byte, []int) {
	return file_internal_proto_logicalResource_proto_rawDescGZIP(), []int{0, 3}
}

func (x *LogicalResource_ResourceCharacteristic) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LogicalResource_ResourceCharacteristic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LogicalResource_ResourceCharacteristic) GetPublicIdentifier() bool {
	if x != nil {
		return x.PublicIdentifier
	}
	return false
}

func (x *LogicalResource_ResourceCharacteristic) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *LogicalResource_ResourceCharacteristic) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

// ResourceRelationship of the LogicalResourceMessage task
type LogicalResource_ResourceRelationship struct {
	state            protoimpl.MessageState                         `protogen:"open.v1"`
	RelationshipType string                                         `protobuf:"bytes,1,opt,name=relationshipType,proto3" json:"relationshipType,omitempty"`
	ValidFor         *LogicalResource_ResourceRelationship_ValidFor `protobuf:"bytes,2,opt,name=validFor,proto3" json:"validFor,omitempty"`
	Resource         *LogicalResource_ResourceRelationship_Resource `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LogicalResource_ResourceRelationship) Reset() {
	*x = LogicalResource_ResourceRelationship{}
	mi := &file_internal_proto_logicalResource_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalResource_ResourceRelationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalResource_ResourceRelationship) ProtoMessage() {}

func (x *LogicalResource_ResourceRelationship) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logicalResource_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalResource_ResourceRelationship.ProtoReflect.Descriptor instead.
func (*LogicalResource_ResourceRelationship) Descriptor() ([]byte, []int) {
	return file_internal_proto_logicalResource_proto_rawDescGZIP(), []int{0, 4}
}

func (x *LogicalResource_ResourceRelationship) GetRelationshipType() string {
	if x != nil {
		return x.RelationshipType
	}
	return ""
}

func (x *LogicalResource_ResourceRelationship) GetValidFor() *LogicalResource_ResourceRelationship_ValidFor {
	if x != nil {
		return x.ValidFor
	}
	return nil
}

func (x *LogicalResource_ResourceRelationship) GetResource() *LogicalResource_ResourceRelationship_Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type LogicalResource_BundledResources struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Href           string                 `protobuf:"bytes,2,opt,name=href,proto3" json:"href,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	BaseType       string                 `protobuf:"bytes,4,opt,name=baseType,proto3" json:"baseType,omitempty"`
	SchemaLocation string                 `protobuf:"bytes,5,opt,name=schemaLocation,proto3" json:"schemaLocation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogicalResource_BundledResources) Reset() {
	*x = LogicalResource_BundledResources{}
	mi := &file_internal_proto_logicalResource_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalResource_BundledResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalResource_BundledResources) ProtoMessage() {}

func (x *LogicalResource_BundledResources) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logicalResource_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalResource_BundledResources.ProtoReflect.Descriptor instead.
func (*LogicalResource_BundledResources) Descriptor() ([]byte, []int) {
	return file_internal_proto_logicalResource_proto_rawDescGZIP(), []int{0, 5}
}

func (x *LogicalResource_BundledResources) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogicalResource_BundledResources) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

func (x *LogicalResource_BundledResources) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LogicalResource_BundledResources) GetBaseType() string {
	if x != nil {
		return x.BaseType
	}
	return ""
}

func (x *LogicalResource_BundledResources) GetSchemaLocation() string {
	if x != nil {
		return x.SchemaLocation
	}
	return ""
}

type LogicalResource_ResourceRelationship_ValidFor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDateTime string                 `protobuf:"bytes,1,opt,name=startDateTime,proto3" json:"startDateTime,omitempty"`
	EndDateTime   string                 `protobuf:"bytes,2,opt,name=endDateTime,proto3" json:"endDateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogicalResource_ResourceRelationship_ValidFor) Reset() {
	*x = LogicalResource_ResourceRelationship_ValidFor{}
	mi := &file_internal_proto_logicalResource_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalResource_ResourceRelationship_ValidFor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalResource_ResourceRelationship_ValidFor) ProtoMessage() {}

func (x *LogicalResource_ResourceRelationship_ValidFor) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logicalResource_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalResource_ResourceRelationship_ValidFor.ProtoReflect.Descriptor instead.
func (*LogicalResource_ResourceRelationship_ValidFor) Descriptor() ([]byte, []int) {
	return file_internal_proto_logicalResource_proto_rawDescGZIP(), []int{0, 4, 0}
}

func (x *LogicalResource_ResourceRelationship_ValidFor) GetStartDateTime() string {
	if x != nil {
		return x.StartDateTime
	}
	return ""
}

func (x *LogicalResource_ResourceRelationship_ValidFor) GetEndDateTime() string {
	if x != nil {
		return x.EndDateTime
	}
	return ""
}

type LogicalResource_ResourceRelationship_Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	BaseType      string                 `protobuf:"bytes,3,opt,name=baseType,proto3" json:"baseType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogicalResource_ResourceRelationship_Resource) Reset() {
	*x = LogicalResource_ResourceRelationship_Resource{}
	mi := &file_internal_proto_logicalResource_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalResource_ResourceRelationship_Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalResource_ResourceRelationship_Resource) ProtoMessage() {}

func (x *LogicalResource_ResourceRelationship_Resource) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logicalResource_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalResource_ResourceRelationship_Resource.ProtoReflect.Descriptor instead.
func (*LogicalResource_ResourceRelationship_Resource) Descriptor() ([]byte, []int) {
	return file_internal_proto_logicalResource_proto_rawDescGZIP(), []int{0, 4, 1}
}

func (x *LogicalResource_ResourceRelationship_Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogicalResource_ResourceRelationship_Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LogicalResource_ResourceRelationship_Resource) GetBaseType() string {
	if x != nil {
		return x.BaseType
	}
	return ""
}

type LogicalResourceResponse_Cost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaxFreeValue  int64                  `protobuf:"varint,1,opt,name=taxFreeValue,proto3" json:"taxFreeValue,omitempty"`
	TaxedValue    int64                  `protobuf:"varint,2,opt,name=taxedValue,proto3" json:"taxedValue,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogicalResourceResponse_Cost) Reset() {
	*x = LogicalResourceResponse_Cost{}
	mi := &file_internal_proto_logicalResource_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalResourceResponse_Cost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalResourceResponse_Cost) ProtoMessage() {}

func (x *LogicalResourceResponse_Cost) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logicalResource_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalResourceResponse_Cost.ProtoReflect.Descriptor instead.
func (*LogicalResourceResponse_Cost) Descriptor() ([]byte, []int) {
	return file_internal_proto_logicalResource_proto_rawDescGZIP(), []int{1, 0}
}

func (x *LogicalResourceResponse_Cost) GetTaxFreeValue() int64 {
	if x != nil {
		return x.TaxFreeValue
	}
	return 0
}

func (x *LogicalResourceResponse_Cost) GetTaxedValue() int64 {
	if x != nil {
		return x.TaxedValue
	}
	return 0
}

func (x *LogicalResourceResponse_Cost) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type LogicalResourceResponse_Note struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorRole    string                 `protobuf:"bytes,1,opt,name=authorRole,proto3" json:"authorRole,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"` // ISO date string
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogicalResourceResponse_Note) Reset() {
	*x = LogicalResourceResponse_Note{}
	mi := &file_internal_proto_logicalResource_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalResourceResponse_Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalResourceResponse_Note) ProtoMessage() {}

func (x *LogicalResourceResponse_Note) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logicalResource_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalResourceResponse_Note.ProtoReflect.Descriptor instead.
func (*LogicalResourceResponse_Note) Descriptor() ([]byte, []int) {
	return file_internal_proto_logicalResource_proto_rawDescGZIP(), []int{1, 1}
}

func (x *LogicalResourceResponse_Note) GetAuthorRole() string {
	if x != nil {
		return x.AuthorRole
	}
	return ""
}

func (x *LogicalResourceResponse_Note) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *LogicalResourceResponse_Note) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *LogicalResourceResponse_Note) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type LogicalResourceResponse_RelatedParty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	BaseType      string                 `protobuf:"bytes,4,opt,name=baseType,proto3" json:"baseType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogicalResourceResponse_RelatedParty) Reset() {
	*x = LogicalResourceResponse_RelatedParty{}
	mi := &file_internal_proto_logicalResource_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalResourceResponse_RelatedParty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalResourceResponse_RelatedParty) ProtoMessage() {}

func (x *LogicalResourceResponse_RelatedParty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logicalResource_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalResourceResponse_RelatedParty.ProtoReflect.Descriptor instead.
func (*LogicalResourceResponse_RelatedParty) Descriptor() ([]byte, []int) {
	return file_internal_proto_logicalResource_proto_rawDescGZIP(), []int{1, 2}
}

func (x *LogicalResourceResponse_RelatedParty) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LogicalResourceResponse_RelatedParty) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *LogicalResourceResponse_RelatedParty) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LogicalResourceResponse_RelatedParty) GetBaseType() string {
	if x != nil {
		return x.BaseType
	}
	return ""
}

type LogicalResourceResponse_ResourceCharacteristic struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Code             string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PublicIdentifier bool                   `protobuf:"varint,3,opt,name=publicIdentifier,proto3" json:"publicIdentifier,omitempty"`
	Value            string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	ValueType        string                 `protobuf:"bytes,5,opt,name=valueType,proto3" json:"valueType,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LogicalResourceResponse_ResourceCharacteristic) Reset() {
	*x = LogicalResourceResponse_ResourceCharacteristic{}
	mi := &file_internal_proto_logicalResource_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalResourceResponse_ResourceCharacteristic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalResourceResponse_ResourceCharacteristic) ProtoMessage() {}

func (x *LogicalResourceResponse_ResourceCharacteristic) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logicalResource_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalResourceResponse_ResourceCharacteristic.ProtoReflect.Descriptor instead.
func (*LogicalResourceResponse_ResourceCharacteristic) Descriptor() ([]byte, []int) {
	return file_internal_proto_logicalResource_proto_rawDescGZIP(), []int{1, 3}
}

func (x *LogicalResourceResponse_ResourceCharacteristic) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LogicalResourceResponse_ResourceCharacteristic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LogicalResourceResponse_ResourceCharacteristic) GetPublicIdentifier() bool {
	if x != nil {
		return x.PublicIdentifier
	}
	return false
}

func (x *LogicalResourceResponse_ResourceCharacteristic) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *LogicalResourceResponse_ResourceCharacteristic) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

// ResourceRelationship of the LogicalResourceMessage task
type LogicalResourceResponse_ResourceRelationship struct {
	state            protoimpl.MessageState                                 `protogen:"open.v1"`
	RelationshipType string                                                 `protobuf:"bytes,1,opt,name=relationshipType,proto3" json:"relationshipType,omitempty"`
	ValidFor         *LogicalResourceResponse_ResourceRelationship_ValidFor `protobuf:"bytes,2,opt,name=validFor,proto3" json:"validFor,omitempty"`
	Resource         *LogicalResourceResponse_ResourceRelationship_Resource `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LogicalResourceResponse_ResourceRelationship) Reset() {
	*x = LogicalResourceResponse_ResourceRelationship{}
	mi := &file_internal_proto_logicalResource_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalResourceResponse_ResourceRelationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalResourceResponse_ResourceRelationship) ProtoMessage() {}

func (x *LogicalResourceResponse_ResourceRelationship) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logicalResource_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalResourceResponse_ResourceRelationship.ProtoReflect.Descriptor instead.
func (*LogicalResourceResponse_ResourceRelationship) Descriptor() ([]byte, []int) {
	return file_internal_proto_logicalResource_proto_rawDescGZIP(), []int{1, 4}
}

func (x *LogicalResourceResponse_ResourceRelationship) GetRelationshipType() string {
	if x != nil {
		return x.RelationshipType
	}
	return ""
}

func (x *LogicalResourceResponse_ResourceRelationship) GetValidFor() *LogicalResourceResponse_ResourceRelationship_ValidFor {
	if x != nil {
		return x.ValidFor
	}
	return nil
}

func (x *LogicalResourceResponse_ResourceRelationship) GetResource() *LogicalResourceResponse_ResourceRelationship_Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type LogicalResourceResponse_BundledResources struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Href           string                 `protobuf:"bytes,2,opt,name=href,proto3" json:"href,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	BaseType       string                 `protobuf:"bytes,4,opt,name=baseType,proto3" json:"baseType,omitempty"`
	SchemaLocation string                 `protobuf:"bytes,5,opt,name=schemaLocation,proto3" json:"schemaLocation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogicalResourceResponse_BundledResources) Reset() {
	*x = LogicalResourceResponse_BundledResources{}
	mi := &file_internal_proto_logicalResource_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalResourceResponse_BundledResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalResourceResponse_BundledResources) ProtoMessage() {}

func (x *LogicalResourceResponse_BundledResources) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logicalResource_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalResourceResponse_BundledResources.ProtoReflect.Descriptor instead.
func (*LogicalResourceResponse_BundledResources) Descriptor() ([]byte, []int) {
	return file_internal_proto_logicalResource_proto_rawDescGZIP(), []int{1, 5}
}

func (x *LogicalResourceResponse_BundledResources) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogicalResourceResponse_BundledResources) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

func (x *LogicalResourceResponse_BundledResources) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LogicalResourceResponse_BundledResources) GetBaseType() string {
	if x != nil {
		return x.BaseType
	}
	return ""
}

func (x *LogicalResourceResponse_BundledResources) GetSchemaLocation() string {
	if x != nil {
		return x.SchemaLocation
	}
	return ""
}

type LogicalResourceResponse_ResourceRelationship_ValidFor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDateTime string                 `protobuf:"bytes,1,opt,name=startDateTime,proto3" json:"startDateTime,omitempty"`
	EndDateTime   string                 `protobuf:"bytes,2,opt,name=endDateTime,proto3" json:"endDateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogicalResourceResponse_ResourceRelationship_ValidFor) Reset() {
	*x = LogicalResourceResponse_ResourceRelationship_ValidFor{}
	mi := &file_internal_proto_logicalResource_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalResourceResponse_ResourceRelationship_ValidFor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalResourceResponse_ResourceRelationship_ValidFor) ProtoMessage() {}

func (x *LogicalResourceResponse_ResourceRelationship_ValidFor) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logicalResource_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalResourceResponse_ResourceRelationship_ValidFor.ProtoReflect.Descriptor instead.
func (*LogicalResourceResponse_ResourceRelationship_ValidFor) Descriptor() ([]byte, []int) {
	return file_internal_proto_logicalResource_proto_rawDescGZIP(), []int{1, 4, 0}
}

func (x *LogicalResourceResponse_ResourceRelationship_ValidFor) GetStartDateTime() string {
	if x != nil {
		return x.StartDateTime
	}
	return ""
}

func (x *LogicalResourceResponse_ResourceRelationship_ValidFor) GetEndDateTime() string {
	if x != nil {
		return x.EndDateTime
	}
	return ""
}

type LogicalResourceResponse_ResourceRelationship_Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	BaseType      string                 `protobuf:"bytes,3,opt,name=baseType,proto3" json:"baseType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogicalResourceResponse_ResourceRelationship_Resource) Reset() {
	*x = LogicalResourceResponse_ResourceRelationship_Resource{}
	mi := &file_internal_proto_logicalResource_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalResourceResponse_ResourceRelationship_Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalResourceResponse_ResourceRelationship_Resource) ProtoMessage() {}

func (x *LogicalResourceResponse_ResourceRelationship_Resource) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_logicalResource_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalResourceResponse_ResourceRelationship_Resource.ProtoReflect.Descriptor instead.
func (*LogicalResourceResponse_ResourceRelationship_Resource) Descriptor() ([]byte, []int) {
	return file_internal_proto_logicalResource_proto_rawDescGZIP(), []int{1, 4, 1}
}

func (x *LogicalResourceResponse_ResourceRelationship_Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogicalResourceResponse_ResourceRelationship_Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LogicalResourceResponse_ResourceRelationship_Resource) GetBaseType() string {
	if x != nil {
		return x.BaseType
	}
	return ""
}

var File_internal_proto_logicalResource_proto protoreflect.FileDescriptor

const file_internal_proto_logicalResource_proto_rawDesc = "" +
	"\n" +
	"$internal/proto/logicalResource.proto\x12\x0flogicalresource\"\xb9\x11\n" +
	"\x0fLogicalResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1a\n" +
	"\bbaseType\x18\x05 \x01(\tR\bbaseType\x12\x1a\n" +
	"\bisBundle\x18\x06 \x01(\bR\bisBundle\x12\x14\n" +
	"\x05value\x18\a \x01(\tR\x05value\x12.\n" +
	"\x12startOperatingDate\x18\b \x01(\tR\x12startOperatingDate\x12*\n" +
	"\x10endOperatingDate\x18\t \x01(\tR\x10endOperatingDate\x120\n" +
	"\x13resourceRecycleDate\x18\n" +
	" \x01(\tR\x13resourceRecycleDate\x12&\n" +
	"\x0eresourceStatus\x18\v \x01(\tR\x0eresourceStatus\x12\"\n" +
	"\fbusinessType\x18\f \x03(\tR\fbusinessType\x12\x1a\n" +
	"\bcategory\x18\r \x03(\tR\bcategory\x129\n" +
	"\x04cost\x18\x0e \x01(\v2%.logicalresource.LogicalResource.CostR\x04cost\x129\n" +
	"\x04note\x18\x0f \x03(\v2%.logicalresource.LogicalResource.NoteR\x04note\x12Q\n" +
	"\frelatedParty\x18\x10 \x03(\v2-.logicalresource.LogicalResource.RelatedPartyR\frelatedParty\x12o\n" +
	"\x16resourceCharacteristic\x18\x11 \x03(\v27.logicalresource.LogicalResource.ResourceCharacteristicR\x16resourceCharacteristic\x12i\n" +
	"\x14resourceRelationship\x18\x12 \x03(\v25.logicalresource.LogicalResource.ResourceRelationshipR\x14resourceRelationship\x12]\n" +
	"\x10bundledResources\x18\x13 \x03(\v21.logicalresource.LogicalResource.BundledResourcesR\x10bundledResources\x12\x1c\n" +
	"\tcreatedAt\x18\x14 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x15 \x01(\tR\tupdatedAt\x1a^\n" +
	"\x04Cost\x12\"\n" +
	"\ftaxFreeValue\x18\x01 \x01(\x03R\ftaxFreeValue\x12\x1e\n" +
	"\n" +
	"taxedValue\x18\x02 \x01(\x03R\n" +
	"taxedValue\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x1af\n" +
	"\x04Note\x12\x1e\n" +
	"\n" +
	"authorRole\x18\x01 \x01(\tR\n" +
	"authorRole\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x1af\n" +
	"\fRelatedParty\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bbaseType\x18\x04 \x01(\tR\bbaseType\x1a\xa0\x01\n" +
	"\x16ResourceCharacteristic\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x10publicIdentifier\x18\x03 \x01(\bR\x10publicIdentifier\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x1c\n" +
	"\tvalueType\x18\x05 \x01(\tR\tvalueType\x1a\x81\x04\n" +
	"\x14ResourceRelationship\x12*\n" +
	"\x10relationshipType\x18\x01 \x01(\tR\x10relationshipType\x12Z\n" +
	"\bvalidFor\x18\x02 \x01(\v2>.logicalresource.LogicalResource.ResourceRelationship.ValidForR\bvalidFor\x12Z\n" +
	"\bresource\x18\x03 \x01(\v2>.logicalresource.LogicalResource.ResourceRelationship.ResourceR\bresource\x1aR\n" +
	"\bValidFor\x12$\n" +
	"\rstartDateTime\x18\x01 \x01(\tR\rstartDateTime\x12 \n" +
	"\vendDateTime\x18\x02 \x01(\tR\vendDateTime\x1aJ\n" +
	"\bResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bbaseType\x18\x03 \x01(\tR\bbaseType\"e\n" +
	"\x10RelationshipType\x12\f\n" +
	"\breliesOn\x10\x00\x12\n" +
	"\n" +
	"\x06bundle\x10\x01\x12\x0e\n" +
	"\n" +
	"dependency\x10\x02\x12\x0f\n" +
	"\vstarterPack\x10\x03\x12\f\n" +
	"\bcapacity\x10\x04\x12\b\n" +
	"\x04pool\x10\x05\x1a\x8e\x01\n" +
	"\x10BundledResources\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04href\x18\x02 \x01(\tR\x04href\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bbaseType\x18\x04 \x01(\tR\bbaseType\x12&\n" +
	"\x0eschemaLocation\x18\x05 \x01(\tR\x0eschemaLocation\"`\n" +
	"\x0eResourceStatus\x12\v\n" +
	"\aCreated\x10\x00\x12\r\n" +
	"\tAvailable\x10\x01\x12\f\n" +
	"\bReserved\x10\x02\x12\t\n" +
	"\x05InUse\x10\x03\x12\v\n" +
	"\aRetired\x10\x04\x12\f\n" +
	"\bDisabled\x10\x05\"\x81\x12\n" +
	"\x17LogicalResourceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1a\n" +
	"\bbaseType\x18\x05 \x01(\tR\bbaseType\x12\x1a\n" +
	"\bisBundle\x18\x06 \x01(\bR\bisBundle\x12\x14\n" +
	"\x05value\x18\a \x01(\tR\x05value\x12.\n" +
	"\x12startOperatingDate\x18\b \x01(\tR\x12startOperatingDate\x12*\n" +
	"\x10endOperatingDate\x18\t \x01(\tR\x10endOperatingDate\x120\n" +
	"\x13resourceRecycleDate\x18\n" +
	" \x01(\tR\x13resourceRecycleDate\x12&\n" +
	"\x0eresourceStatus\x18\v \x01(\tR\x0eresourceStatus\x12\"\n" +
	"\fbusinessType\x18\f \x03(\tR\fbusinessType\x12\x1a\n" +
	"\bcategory\x18\r \x03(\tR\bcategory\x12A\n" +
	"\x04cost\x18\x0e \x01(\v2-.logicalresource.LogicalResourceResponse.CostR\x04cost\x12A\n" +
	"\x04note\x18\x0f \x03(\v2-.logicalresource.LogicalResourceResponse.NoteR\x04note\x12Y\n" +
	"\frelatedParty\x18\x10 \x03(\v25.logicalresource.LogicalResourceResponse.RelatedPartyR\frelatedParty\x12w\n" +
	"\x16resourceCharacteristic\x18\x11 \x03(\v2?.logicalresource.LogicalResourceResponse.ResourceCharacteristicR\x16resourceCharacteristic\x12q\n" +
	"\x14resourceRelationship\x18\x12 \x03(\v2=.logicalresource.LogicalResourceResponse.ResourceRelationshipR\x14resourceRelationship\x12e\n" +
	"\x10bundledResources\x18\x13 \x03(\v29.logicalresource.LogicalResourceResponse.BundledResourcesR\x10bundledResources\x12\x1c\n" +
	"\tcreatedAt\x18\x14 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x15 \x01(\tR\tupdatedAt\x1a^\n" +
	"\x04Cost\x12\"\n" +
	"\ftaxFreeValue\x18\x01 \x01(\x03R\ftaxFreeValue\x12\x1e\n" +
	"\n" +
	"taxedValue\x18\x02 \x01(\x03R\n" +
	"taxedValue\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x1af\n" +
	"\x04Note\x12\x1e\n" +
	"\n" +
	"authorRole\x18\x01 \x01(\tR\n" +
	"authorRole\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x1af\n" +
	"\fRelatedParty\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bbaseType\x18\x04 \x01(\tR\bbaseType\x1a\xa0\x01\n" +
	"\x16ResourceCharacteristic\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x10publicIdentifier\x18\x03 \x01(\bR\x10publicIdentifier\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x1c\n" +
	"\tvalueType\x18\x05 \x01(\tR\tvalueType\x1a\x91\x04\n" +
	"\x14ResourceRelationship\x12*\n" +
	"\x10relationshipType\x18\x01 \x01(\tR\x10relationshipType\x12b\n" +
	"\bvalidFor\x18\x02 \x01(\v2F.logicalresource.LogicalResourceResponse.ResourceRelationship.ValidForR\bvalidFor\x12b\n" +
	"\bresource\x18\x03 \x01(\v2F.logicalresource.LogicalResourceResponse.ResourceRelationship.ResourceR\bresource\x1aR\n" +
	"\bValidFor\x12$\n" +
	"\rstartDateTime\x18\x01 \x01(\tR\rstartDateTime\x12 \n" +
	"\vendDateTime\x18\x02 \x01(\tR\vendDateTime\x1aJ\n" +
	"\bResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bbaseType\x18\x03 \x01(\tR\bbaseType\"e\n" +
	"\x10RelationshipType\x12\f\n" +
	"\breliesOn\x10\x00\x12\n" +
	"\n" +
	"\x06bundle\x10\x01\x12\x0e\n" +
	"\n" +
	"dependency\x10\x02\x12\x0f\n" +
	"\vstarterPack\x10\x03\x12\f\n" +
	"\bcapacity\x10\x04\x12\b\n" +
	"\x04pool\x10\x05\x1a\x8e\x01\n" +
	"\x10BundledResources\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04href\x18\x02 \x01(\tR\x04href\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bbaseType\x18\x04 \x01(\tR\bbaseType\x12&\n" +
	"\x0eschemaLocation\x18\x05 \x01(\tR\x0eschemaLocation\"`\n" +
	"\x0eResourceStatus\x12\v\n" +
	"\aCreated\x10\x00\x12\r\n" +
	"\tAvailable\x10\x01\x12\f\n" +
	"\bReserved\x10\x02\x12\t\n" +
	"\x05InUse\x10\x03\x12\v\n" +
	"\aRetired\x10\x04\x12\f\n" +
	"\bDisabled\x10\x05\"q\n" +
	"\x13PatchLogicalRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12J\n" +
	"\x0flogicalResource\x18\x02 \x01(\v2 .logicalresource.LogicalResourceR\x0flogicalResource2\xe5\x01\n" +
	"\x16LogicalResourceService\x12c\n" +
	"\x15CreateLogicalResource\x12 .logicalresource.LogicalResource\x1a(.logicalresource.LogicalResourceResponse\x12f\n" +
	"\x14PatchLogicalResource\x12$.logicalresource.PatchLogicalRequest\x1a(.logicalresource.LogicalResourceResponseBAZ?drm-bulk-service/internal/proto/logicalresource;logicalresourceb\x06proto3"

var (
	file_internal_proto_logicalResource_proto_rawDescOnce sync.Once
	file_internal_proto_logicalResource_proto_rawDescData []byte
)

func file_internal_proto_logicalResource_proto_rawDescGZIP() []byte {
	file_internal_proto_logicalResource_proto_rawDescOnce.Do(func() {
		file_internal_proto_logicalResource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_logicalResource_proto_rawDesc), len(file_internal_proto_logicalResource_proto_rawDesc)))
	})
	return file_internal_proto_logicalResource_proto_rawDescData
}

var file_internal_proto_logicalResource_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_internal_proto_logicalResource_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_internal_proto_logicalResource_proto_goTypes = []any{
	(LogicalResource_ResourceStatus)(0),                                // 0: logicalresource.LogicalResource.ResourceStatus
	(LogicalResource_ResourceRelationship_RelationshipType)(0),         // 1: logicalresource.LogicalResource.ResourceRelationship.RelationshipType
	(LogicalResourceResponse_ResourceStatus)(0),                        // 2: logicalresource.LogicalResourceResponse.ResourceStatus
	(LogicalResourceResponse_ResourceRelationship_RelationshipType)(0), // 3: logicalresource.LogicalResourceResponse.ResourceRelationship.RelationshipType
	(*LogicalResource)(nil),                                            // 4: logicalresource.LogicalResource
	(*LogicalResourceResponse)(nil),                                    // 5: logicalresource.LogicalResourceResponse
	(*PatchLogicalRequest)(nil),                                        // 6: logicalresource.PatchLogicalRequest
	(*LogicalResource_Cost)(nil),                                       // 7: logicalresource.LogicalResource.Cost
	(*LogicalResource_Note)(nil),                                       // 8: logicalresource.LogicalResource.Note
	(*LogicalResource_RelatedParty)(nil),                               // 9: logicalresource.LogicalResource.RelatedParty
	(*LogicalResource_ResourceCharacteristic)(nil),                     // 10: logicalresource.LogicalResource.ResourceCharacteristic
	(*LogicalResource_ResourceRelationship)(nil),                       // 11: logicalresource.LogicalResource.ResourceRelationship
	(*LogicalResource_BundledResources)(nil),                           // 12: logicalresource.LogicalResource.BundledResources
	(*LogicalResource_ResourceRelationship_ValidFor)(nil),              // 13: logicalresource.LogicalResource.ResourceRelationship.ValidFor
	(*LogicalResource_ResourceRelationship_Resource)(nil),              // 14: logicalresource.LogicalResource.ResourceRelationship.Resource
	(*LogicalResourceResponse_Cost)(nil),                               // 15: logicalresource.LogicalResourceResponse.Cost
	(*LogicalResourceResponse_Note)(nil),                               // 16: logicalresource.LogicalResourceResponse.Note
	(*LogicalResourceResponse_RelatedParty)(nil),                       // 17: logicalresource.LogicalResourceResponse.RelatedParty
	(*LogicalResourceResponse_ResourceCharacteristic)(nil),             // 18: logicalresource.LogicalResourceResponse.ResourceCharacteristic
	(*LogicalResourceResponse_ResourceRelationship)(nil),               // 19: logicalresource.LogicalResourceResponse.ResourceRelationship
	(*LogicalResourceResponse_BundledResources)(nil),                   // 20: logicalresource.LogicalResourceResponse.BundledResources
	(*LogicalResourceResponse_ResourceRelationship_ValidFor)(nil),      // 21: logicalresource.LogicalResourceResponse.ResourceRelationship.ValidFor
	(*LogicalResourceResponse_ResourceRelationship_Resource)(nil),      // 22: logicalresource.LogicalResourceResponse.ResourceRelationship.Resource
}
var file_internal_proto_logicalResource_proto_depIdxs = []int32{
	7,  // 0: logicalresource.LogicalResource.cost:type_name -> logicalresource.LogicalResource.Cost
	8,  // 1: logicalresource.LogicalResource.note:type_name -> logicalresource.LogicalResource.Note
	9,  // 2: logicalresource.LogicalResource.relatedParty:type_name -> logicalresource.LogicalResource.RelatedParty
	10, // 3: logicalresource.LogicalResource.resourceCharacteristic:type_name -> logicalresource.LogicalResource.ResourceCharacteristic
	11, // 4: logicalresource.LogicalResource.resourceRelationship:type_name -> logicalresource.LogicalResource.ResourceRelationship
	12, // 5: logicalresource.LogicalResource.bundledResources:type_name -> logicalresource.LogicalResource.BundledResources
	15, // 6: logicalresource.LogicalResourceResponse.cost:type_name -> logicalresource.LogicalResourceResponse.Cost
	16, // 7: logicalresource.LogicalResourceResponse.note:type_name -> logicalresource.LogicalResourceResponse.Note
	17, // 8: logicalresource.LogicalResourceResponse.relatedParty:type_name -> logicalresource.LogicalResourceResponse.RelatedParty
	18, // 9: logicalresource.LogicalResourceResponse.resourceCharacteristic:type_name -> logicalresource.LogicalResourceResponse.ResourceCharacteristic
	19, // 10: logicalresource.LogicalResourceResponse.resourceRelationship:type_name -> logicalresource.LogicalResourceResponse.ResourceRelationship
	20, // 11: logicalresource.LogicalResourceResponse.bundledResources:type_name -> logicalresource.LogicalResourceResponse.BundledResources
	4,  // 12: logicalresource.PatchLogicalRequest.logicalResource:type_name -> logicalresource.LogicalResource
	13, // 13: logicalresource.LogicalResource.ResourceRelationship.validFor:type_name -> logicalresource.LogicalResource.ResourceRelationship.ValidFor
	14, // 14: logicalresource.LogicalResource.ResourceRelationship.resource:type_name -> logicalresource.LogicalResource.ResourceRelationship.Resource
	21, // 15: logicalresource.LogicalResourceResponse.ResourceRelationship.validFor:type_name -> logicalresource.LogicalResourceResponse.ResourceRelationship.ValidFor
	22, // 16: logicalresource.LogicalResourceResponse.ResourceRelationship.resource:type_name -> logicalresource.LogicalResourceResponse.ResourceRelationship.Resource
	4,  // 17: logicalresource.LogicalResourceService.CreateLogicalResource:input_type -> logicalresource.LogicalResource
	6,  // 18: logicalresource.LogicalResourceService.PatchLogicalResource:input_type -> logicalresource.PatchLogicalRequest
	5,  // 19: logicalresource.LogicalResourceService.CreateLogicalResource:output_type -> logicalresource.LogicalResourceResponse
	5,  // 20: logicalresource.LogicalResourceService.PatchLogicalResource:output_type -> logicalresource.LogicalResourceResponse
	19, // [19:21] is the sub-list for method output_type
	17, // [17:19] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_internal_proto_logicalResource_proto_init() }
func file_internal_proto_logicalResource_proto_init() {
	if File_internal_proto_logicalResource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_logicalResource_proto_rawDesc), len(file_internal_proto_logicalResource_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_logicalResource_proto_goTypes,
		DependencyIndexes: file_internal_proto_logicalResource_proto_depIdxs,
		EnumInfos:         file_internal_proto_logicalResource_proto_enumTypes,
		MessageInfos:      file_internal_proto_logicalResource_proto_msgTypes,
	}.Build()
	File_internal_proto_logicalResource_proto = out.File
	file_internal_proto_logicalResource_proto_goTypes = nil
	file_internal_proto_logicalResource_proto_depIdxs = nil
}
