// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.3
// source: internal/proto/logicalResource.proto

package logicalresource

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogicalResourceService_CreateLogicalResource_FullMethodName = "/logicalresource.LogicalResourceService/CreateLogicalResource"
	LogicalResourceService_PatchLogicalResource_FullMethodName  = "/logicalresource.LogicalResourceService/PatchLogicalResource"
)

// LogicalResourceServiceClient is the client API for LogicalResourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogicalResourceServiceClient interface {
	CreateLogicalResource(ctx context.Context, in *LogicalResource, opts ...grpc.CallOption) (*LogicalResourceResponse, error)
	PatchLogicalResource(ctx context.Context, in *PatchLogicalRequest, opts ...grpc.CallOption) (*LogicalResourceResponse, error)
}

type logicalResourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogicalResourceServiceClient(cc grpc.ClientConnInterface) LogicalResourceServiceClient {
	return &logicalResourceServiceClient{cc}
}

func (c *logicalResourceServiceClient) CreateLogicalResource(ctx context.Context, in *LogicalResource, opts ...grpc.CallOption) (*LogicalResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogicalResourceResponse)
	err := c.cc.Invoke(ctx, LogicalResourceService_CreateLogicalResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicalResourceServiceClient) PatchLogicalResource(ctx context.Context, in *PatchLogicalRequest, opts ...grpc.CallOption) (*LogicalResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogicalResourceResponse)
	err := c.cc.Invoke(ctx, LogicalResourceService_PatchLogicalResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogicalResourceServiceServer is the server API for LogicalResourceService service.
// All implementations must embed UnimplementedLogicalResourceServiceServer
// for forward compatibility.
type LogicalResourceServiceServer interface {
	CreateLogicalResource(context.Context, *LogicalResource) (*LogicalResourceResponse, error)
	PatchLogicalResource(context.Context, *PatchLogicalRequest) (*LogicalResourceResponse, error)
	mustEmbedUnimplementedLogicalResourceServiceServer()
}

// UnimplementedLogicalResourceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogicalResourceServiceServer struct{}

func (UnimplementedLogicalResourceServiceServer) CreateLogicalResource(context.Context, *LogicalResource) (*LogicalResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLogicalResource not implemented")
}
func (UnimplementedLogicalResourceServiceServer) PatchLogicalResource(context.Context, *PatchLogicalRequest) (*LogicalResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PatchLogicalResource not implemented")
}
func (UnimplementedLogicalResourceServiceServer) mustEmbedUnimplementedLogicalResourceServiceServer() {
}
func (UnimplementedLogicalResourceServiceServer) testEmbeddedByValue() {}

// UnsafeLogicalResourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogicalResourceServiceServer will
// result in compilation errors.
type UnsafeLogicalResourceServiceServer interface {
	mustEmbedUnimplementedLogicalResourceServiceServer()
}

func RegisterLogicalResourceServiceServer(s grpc.ServiceRegistrar, srv LogicalResourceServiceServer) {
	// If the following call panics, it indicates UnimplementedLogicalResourceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogicalResourceService_ServiceDesc, srv)
}

func _LogicalResourceService_CreateLogicalResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogicalResource)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicalResourceServiceServer).CreateLogicalResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogicalResourceService_CreateLogicalResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicalResourceServiceServer).CreateLogicalResource(ctx, req.(*LogicalResource))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicalResourceService_PatchLogicalResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchLogicalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicalResourceServiceServer).PatchLogicalResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogicalResourceService_PatchLogicalResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicalResourceServiceServer).PatchLogicalResource(ctx, req.(*PatchLogicalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogicalResourceService_ServiceDesc is the grpc.ServiceDesc for LogicalResourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogicalResourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logicalresource.LogicalResourceService",
	HandlerType: (*LogicalResourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLogicalResource",
			Handler:    _LogicalResourceService_CreateLogicalResource_Handler,
		},
		{
			MethodName: "PatchLogicalResource",
			Handler:    _LogicalResourceService_PatchLogicalResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/logicalResource.proto",
}
